### ISSUE TITLE
Clarify meaning of first column in output

### ISSUE THREAD

**Issue by lkapelevich** [odow/SDDP.jl#113]
I don't think there are updated docs clarifying this at the moment. Just leaving this here to answer a question.

The first column is either a single value or a confidence interval from a Monte Carlo simulation. When the entry is a single value, its is the objective from a single (and the most recent) forward pass in SDDP. The single value is not an average.

To compute a statistical upper bound, you can:
1) Use the `simulate` function after you finished solving your model
2) If you want to get bounds while solving, use the `simulation` keyword argument in the `solve` function. You can control how frequently these will run.

There is an example of both in: https://github.com/odow/SDDP.jl/blob/master/examples/Newsvendor/newsvendor.jl.

The first time we solve the model, we set the frequency of simulations to be every 10 iterations:
https://github.com/odow/SDDP.jl/blob/master/examples/Newsvendor/newsvendor.jl#L99
So in the 10th iteration you will see a calculation of % Gap and a confidence interval.

Then there is an example using the simulate function:
https://github.com/odow/SDDP.jl/blob/master/examples/Newsvendor/newsvendor.jl#L134
And in the line below we compute the mean objective of 500 simulations.

**Comment by odow** [comment]
This was addressed partially in https://github.com/odow/SDDP.jl/pull/112. The docs should update in the next few minutes.

**Comment by odow** [comment]
The new docs address this:
https://odow.github.io/SDDP.jl/latest/tutorial/02_rhs_noise.html#Solving-the-problem-1
