### ISSUE TITLE
Proposal: Stopping Rules

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#124]
something along the lines of
```julia
abstract type StoppingRule end

struct BoundStalling <: StoppingRule
    N::Int
    tol::Float64
end

function stoppingrule(sr::BoundStalling, m::SDDPModel)
    for i in 0:min(length(m.log) - 2, sr.N)
        if abs(m.log[end - i].bound - m.log[end-i-1].bound) > sr.tol
            return false
        end
    end
    return true
end

# usage
solve(m,
    stopping_rules = [
        BoundStalling(5, 0.0)
    ]
)

```

**Comment by frapac** [comment]
I like this. However, I remember that Shapiro considers that this stopping test could me misguided, especially when SDDP converges very slowly. Maybe we should prevent the users that SDDP may be far from convergence? But taking this criteria is a better idea than considering a fixed number of iterations, AFAIK. :blush:

**Comment by odow** [comment]
I agree with Shapiro. But I prefer running a fixed number of iterations,  stimulating the policy, and visually inspecting the solution. Unless you have a deterministic upper bound (e.g. your OO paper), any rules are potentially misguided.
