### ISSUE TITLE
Suggestion to use writeLP

### ISSUE THREAD

**Issue by Thuener** [odow/SDDP.jl#127]
Just a suggestion to use JuMP.writeLP(sp, filepath; genericnames=false) instead of WriteMPS. It is easier to interpret the .lp and find the model issue.
https://github.com/odow/SDDP.jl/blob/dbf58d7472ca04df5347aa5bf5dbc1e15bc95120/src/utilities.jl#L189

**Comment by odow** [comment]
PR's accepted.
