### ISSUE TITLE
About a multidimensional random variable in RHS noise

### ISSUE THREAD

**Issue by sarpon** [odow/SDDP.jl#132]
Hey Guys:

I'm having a little problem in declaring a multidimensional random variable, which represents the following:
- For every scenario "i" the radiation in every hour our a day.

 For example let us assume that a day has 4 hours then
```julia
gen = [0.01 0.91 4.11 7.54 ;
       0.00 0.06 1.06 3.76 ;
       0.02 1.14 5.26 8.01 ]
``` 
Where every row represents and scenario and every column a particular Hour. Then `gen[1,1]` is the radiation in the first hour of a day for the first scenario and `gen[1,4]` is the generation in the fourth hour of the day for the same scenario. Note that the scenario is fixed across the hours of the day, this means that if we sample the first scenario we are not allowed to change it during the day.

Now I want to create one scenario for every hour. I have tried the following two codes.

**First Approach**
```julia
for per = 1:4
@rhsnoise(sp, G = [gen[1,per],gen[2,per],gen[3,per]], XPA[per] + YPA[per] + ZPA[per] - DN[per] + SN[per] == G)
setnoiseprobability!(sp, [0.12087912087912088, 0.12637362637362637, 0.75274725274725274])
end
```
**Second Approach**
```julia
@rhsnoises(sp, i=[1,2,3], begin
                XPA[1] + YPA[1] + ZPA[1] - DN[1] + SN[1] == gen[i,1]
                XPA[2] + YPA[2] + ZPA[2] - DN[2] + SN[2] == gen[i,2]
                XPA[3] + YPA[3] + ZPA[3] - DN[3] + SN[3] == gen[i,3]
                XPA[4] + YPA[4] + ZPA[4] - DN[4] + SN[4] == gen[i,4]
end)
setnoiseprobability!(sp, [0.12087912087912088, 0.12637362637362637, 0.75274725274725274])
```
What I think is that both approaches leads me to changes in the scenarios between hours, for example:
For one node in the tree I suspect that this kind of contraints are been added.
```julia
 XPA[1] + YPA[1] + ZPA[1] - DN[1] + SN[1] == gen[1,1]
 XPA[2] + YPA[2] + ZPA[2] - DN[2] + SN[2] == gen[2,2]
 XPA[3] + YPA[3] + ZPA[3] - DN[3] + SN[3] == gen[2,3]
 XPA[4] + YPA[4] + ZPA[4] - DN[4] + SN[4] == gen[3,4]
```
But I need that for one node in the tree the constraints that should be added are the following:
```julia
 XPA[1] + YPA[1] + ZPA[1] - DN[1] + SN[1] == gen[1,1]
 XPA[2] + YPA[2] + ZPA[2] - DN[2] + SN[2] == gen[1,2]
 XPA[3] + YPA[3] + ZPA[3] - DN[3] + SN[3] == gen[1,3]
 XPA[4] + YPA[4] + ZPA[4] - DN[4] + SN[4] == gen[1,4]
```

**Comment by odow** [comment]
You are correct, both approaches are identical. You can format the first approach a bit nicer using Julia's array slicing syntax:
```julia
for per = 1:4
    @rhsnoise(sp, G = gen[:, per], 
        XPA[per] + YPA[per] + ZPA[per] - DN[per] + SN[per] == G
    )
end
setnoiseprobability!(sp, [0.12087912087912088, 0.12637362637362637, 0.75274725274725274])
```

If you're getting the wrong answer, I suggest the problem is somewhere else in your code. 

Is it a very big example? If you don't mind making it public, I can have a look at add it as an example. It's great that you know the deterministic equivalent as well.

p.s. I've formatted your code by surrounding it in triple back ticks ` ``` `

**Comment by sarpon** [comment]
So both of them leads me to ??

```julia
 XPA[1] + YPA[1] + ZPA[1] - DN[1] + SN[1] == gen[1,1]
 XPA[2] + YPA[2] + ZPA[2] - DN[2] + SN[2] == gen[1,2]
 XPA[3] + YPA[3] + ZPA[3] - DN[3] + SN[3] == gen[1,3]
 XPA[4] + YPA[4] + ZPA[4] - DN[4] + SN[4] == gen[1,4]
```

about the problem I think that I all ready solved the problem, I was making a mistake in the objective function. I will ask if I can make the problem public.

**Comment by odow** [comment]
> So both of them leads me to ??

Yes. In each stage, this will add 3 stagewise-independent realizations of the RHS noise term. In realization `i=1,2,3`, there will be constraints such that:
```julia
 XPA[1] + YPA[1] + ZPA[1] - DN[1] + SN[1] == gen[i,1]
 XPA[2] + YPA[2] + ZPA[2] - DN[2] + SN[2] == gen[i,2]
 XPA[3] + YPA[3] + ZPA[3] - DN[3] + SN[3] == gen[i,3]
 XPA[4] + YPA[4] + ZPA[4] - DN[4] + SN[4] == gen[i,4]
```

If you haven't seen, I've been writing docs for the last few days:
https://odow.github.io/SDDP.jl/latest/
My task for today is to begin writing an intro to SDDP tutorial.

> I will ask if I can make the problem public.

No rush. It's great that you got it working.

**Comment by odow** [comment]
This is covered in Tutorial Eight of the new docs:
https://odow.github.io/SDDP.jl/latest/tutorial/08_odds_and_ends.html#Multiple-RHS-noise-constraints-1

Please re-open if it isn't clear.
