### ISSUE TITLE
Get dual variables out of the simulation

### ISSUE THREAD

**Issue by adow031** [odow/SDDP.jl#156]
It doesn't appear the code is currently set up to allow the easy extraction of dual variables of the subproblem constraints. Could you point me to the place in the code that creates a dictionary reference for a variable 'x' as ':x'?

I'd like to do the same for the constraints.

**Comment by lkapelevich** [comment]
@nsepulvedam - you had the same question

**Comment by odow** [comment]
On the contrary, thanks to @bfpc (https://github.com/odow/SDDP.jl/pull/125), it should be easy.

This just needs docs.

**Comment by adow031** [comment]
Thanks; perhaps I should update my 2017 version of SDDP.jl...nah I've got too much stuff to stash.
