### ISSUE TITLE
Style Fixes

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#166]
I'm about to embark on a large re-write of this library. As part of that, I will be updating the code to be much more readable. As such, SDDP.jl will be adopting the [JuMP style guide](http://www.juliaopt.org/JuMP.jl/latest/style.html).

This issue will track the bits I have updated.
- [x] cut oracles https://github.com/odow/SDDP.jl/pull/164
- [x] risk measures https://github.com/odow/SDDP.jl/pull/165
- [ ] price interpolation
- [ ] defaultvaluefunction
- [ ] deprecate
- [ ] experimental
- [ ] JuMPfunctions
- [ ] MIT_licensedcode
- [ ] noises
- [ ] print
- [ ] SDDP.jl
- [ ] simulate
- [ ] solve_asynchronous
- [ ] states
- [ ] typedefinitions
- [ ] utilities
- [ ] `/test`
- [ ] `/examples`

**Comment by viniciusmotta4** [comment]
Hi, I am interested in contributing a bit in this part of the project. Would it be possible?

**Comment by viniciusmotta4** [comment]
Hi @odow, I would be happy to help with the Kokako.jl :). I will probably be available to do so towards the beginning of january :)
