### ISSUE TITLE
2-dim tuple for noise

### ISSUE THREAD

**Issue by lorenzoreus** [odow/SDDP.jl#176]
Dear Oscar, 

I'm trying to implement a process for 2 variables in the price interpolation scheme. 
Specifically I want to have a noise with a simultaneous but different movement for each variable. 
The DiscreteDistribution only allows a vector (N,1) of posibble values for the N possible realizations. But I need to specify a matrix of (N,2) size to include all posibble values. Is it somehow possible  to create a noise for DynamicPriceInterpolation in this case? 

Thanks!

**Comment by odow** [comment]
The answer is just to create a vector of the Cartesian product of the discrete random variables.

```julia
# Support and probabilities of first random variable:
support_A = [1, 2, 3]
probability_A = [0.5, 0.2, 0.3]

# Support and probabilities of second random variable:
support_B = [5, 6]
probability_B = [0.5, 0.5]

# Vector of joint-supports:
supports = [(a, b) for a in support_A for b in support_B]

# Assuming that the random variables are independent
probabilities = [a * b for a in probability_A for b in probability_B]

# Form a discrete distribution
noise_distribution = DiscreteDistribution(supports, probability)

# Now the argument `noise` in the `dynamics` function will be a tuple `(a, b)`.
```

**Comment by lorenzoreus** [comment]
Thanks Oscar!
Following the same approach if I want to add this noise as a tuple. how do operations work?
For example if I have 

function modeldynamics(price,noise)
        a1=price+noise 
        return a1
end
HOw price is defined? Is it also a tuple or an array? Is the + adding tuples componentwise? 
i) How should I enter min_price? As an array or tuple? 
ii) How do I call the component of this price in the SDDPmodel ? 
iii) Something that applies for one-dim price process too. Can I write a constraint in terms of the price? I've only seen example where prices are in the @stageobjective with the syntax "price->" 

Thanks for everything! I really appreaciate your help.

**Comment by odow** [comment]
> HOw price is defined? Is it also a tuple or an array? 

The riverchain example demonstrates N-dimensional prices. In particular
https://github.com/odow/SDDP.jl/blob/d90faae19c90f1fa03636ebe1cee92b083c355c2/examples/PriceInterpolation/riverchain.jl#L68-L73

> Is the + adding tuples componentwise?

This isn't defined in Julia. It will error. You have to do it yourself.

> i) How should I enter min_price? As an array or tuple?

See first comment.

> ii) How do I call the component of this price in the SDDPmodel ?

It will be passed in as a tuple, so access it like a tuple.

https://github.com/odow/SDDP.jl/blob/d90faae19c90f1fa03636ebe1cee92b083c355c2/examples/PriceInterpolation/riverchain.jl#L117-L121

> iii) Something that applies for one-dim price process too. Can I write a constraint in terms of the price? I've only seen example where prices are in the `@stageobjective` with the syntax "price->"

Unfortunately, this is never allowed. One key assumption that we make in our paper is that price is independent of the states and actions in the model. 

If you mean put a constraint in price (e.g., `clamp(price, 0, 1)`), then this is allowed in some circumstances. It gets a bit tricky, but you need to ensure that concavity of the LP is maintained through this price mapping. In general, constraints such as this clamp destroy that concavity. [Caveat emptor](https://en.wikipedia.org/wiki/Caveat_emptor). It's up to you if this is a problem. If it isn't you'll get a good heuristic with no guarantee of global optimality.

**Comment by lorenzoreus** [comment]
Thanks oscar. Very clear explanations. 

And one last question related to this issue of price interpolation scheme 
Can I somehow keep the current price (not the  price at the next stage that includes the noise) as a state variable? I need to use this value, which is known at stage t, in a constraint.

**Comment by odow** [comment]
> I need to use this value, which is known at stage t, in a constraint.

In almost all cases, you can't use the price in a constraint (that is, a JuMP `@constraint` constraint). The library purposefully excludes this possibility.

If you need to use the price in the prior stage in the price dynamics (for example, an auto-regressive process with lag two), you can augment the price-state dimension so it is a tuple of `(price[t], price[t-1])`.

**Comment by lorenzoreus** [comment]
ok! thanks again.
