### ISSUE TITLE
Converged status is overwritten

### ISSUE THREAD

**Issue by Thuener** [odow/SDDP.jl#18]
The variables status and keep_iterating here:
https://github.com/odow/SDDP.jl/blob/d88426e4e9467d816922a59dd5e9c9bdebc4a716/src/SDDP.jl#L288

are overwritten on this line
https://github.com/odow/SDDP.jl/blob/d88426e4e9467d816922a59dd5e9c9bdebc4a716/src/SDDP.jl#L304

**Comment by odow** [comment]
I'm fairly sure if converged is set earlier, it should still be converged in the later test.
