### ISSUE TITLE
SDDP.simulate with vectors

### ISSUE THREAD

**Issue by yakyak462** [odow/SDDP.jl#183]
I am trying to use the simple LinearGraphPolicy. The example in the Kokako tutorial works. However, if I use a multidimensional control variable instead of only single dimensional control variables, I get the error
```
ERROR: LoadError: MethodError: no method matching value(::Array{VariableRef,1})
```
when I run the command 
```
simulations = SDDP.simulate(model, 1, [:controlvar, ]).
```
Running simulations = SDDP.simulate(model, 1) works fine, but then of course I cannot access the solution. Am I misunderstanding something?

**Comment by odow** [comment]
Nope. This is a bug.

**Comment by odow** [comment]
This should be fixed on the latest `merge_kokako` branch. You might need to run `] up SDDP`.

**Comment by yakyak462** [comment]
Works, thanks!
