### ISSUE TITLE
Saving trained model

### ISSUE THREAD

**Issue by yakyak462** [odow/SDDP.jl#184]
Is there a way to save a trained model?

**Comment by odow** [comment]
Not yet. Please keep these issues coming! I'll attack this today.

**Comment by odow** [comment]
Latest commit on `merge_kokako` introduces `SDDP.write_cuts_to_file` and `SDDP.read_cuts_from_file`.

We don't support writing the full JuMP model (yet) because that's a much harder problem, although I have a few ideas along that front https://github.com/odow/MathOptFormat.jl/pull/51
