### ISSUE TITLE
SDDP.write_subproblem_to_file

### ISSUE THREAD

**Issue by yakyak462** [odow/SDDP.jl#193]
I did `] up SDDP` but `SDDP.write_subproblem_to_file` doesn't seem to be working for me.
I get the error: 
```
help?> SDDP.write_subproblem_to_file
  No documentation found.
  Binding SDDP.write_subproblem_to_file does not exist.
```

**Comment by odow** [comment]
It should work if you're on the latest `master` branch. Here is the documentation: https://odow.github.io/SDDP.jl/latest/tutorial/08_debugging/#Writing-subproblems-to-file-1

What is the output of 
```julia
] st
```

Try
```julia
] free SDDP
] up SDDP
```

**Comment by yakyak462** [comment]
My bad, and I'm not sure why ] up didn't work. Did ] add SDDP with success and it updated to newer commit on master.

**Comment by odow** [comment]
Glad you got it working.
