### ISSUE TITLE
Proposal: parallelisation schemes

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#196]
We should re-implement a parallel version of the algorithm. There are a few options, and I'm not sure which is the best to implement.

- Asynchronous complete iterations (a la `release-v0`)
    Pros: simple to implement
    Cons: lots of communication between processes (we're passing looots of cuts around), scales well onto a single desktop, but it doesn't scale well on HPC

- Parallel solves in backward pass (https://github.com/odow/SDDP.jl/issues/159)
    Pros: probably fast? Esp. if lots of noise realizations
    Cons: complicated to implement, Gurobi et al are reeeeally fast at re-solving changes in the RHS

- More complicated schemes: distribute each node (+children) in the graph to a different process and have them continually solving/re-solving
    Pros: this probably works well?
    Cons: lots of cuts being passed again, hard to implement?

**Comment by aferragu** [comment]
Continuing on the discussion on parallel solves in backward pass, can you explain what would be the main bottleneck for implementation? As I see, it works in the style of mapreduce, where map is "solve the subproblem for every noise realization in every child node" and reduce is average over `child.probability * noise.probability`. Of course, the whole model should be available to every computing instance, which may be expensive in some sense, but the `update_value_function` may not be that complicated.

I'm not an expert on HPC by the way...just trying to learn where the challenges are...

**Comment by odow** [comment]
So, the main issues are this:
 - Given an LP, solvers can *very* efficiently solve variations (e.g., changes in the RHS)
 - If we distribute the stage problems over processors, the steps involved to generate a cut are
   - send the state at which we want to evaluate from a master process to each slave process
   - solve each process (no transfer)
   - send the optimal solution(s) from each process back to a master
   - construct a cut on master (no transfer)
   - potentially run cut-selection at the master
   - distribute the cut to each process
   - potentially run cut-selection at the slave
 - The main bottle neck is sending the state to the slave and retrieving the solution, and then sending the cut back to the slave.
 - It's really hard to make this faster than Gurobi doing a few simplex pivots for a change in the RHS

If you have a v. large number of noise terms, then it might be a better idea to sub-sample rather than parallelize.

**Comment by aferragu** [comment]
> **The main bottle neck is sending the state to the slave and retrieving the solution, and then sending the cut back to the slave.**

Ok. I think I see the issue. Just to be clear. the new `SDDP.parameterize` which enables using JuMP.fix is what makes re-solving noises faster?

> If you have a v. large number of noise terms, then it might be a better idea to sub-sample rather than parallelize.

This is indeed our case and what we are discussing in #177. I hope we can contribute there shortly.

**Comment by odow** [comment]
> the new SDDP.parameterize which enables using JuMP.fix is what makes re-solving noises faster?

Essentially, yes. If you use `set_coefficient`, then this re-solves aren't as fast (they're changing coefficients in the A matrix, rather than an element in the RHS vector or in the objective).

**Comment by aferragu** [comment]
Ok. Thanks!
