### ISSUE TITLE
Statistical stopping rule

### ISSUE THREAD

**Issue by aferragu** [odow/SDDP.jl#204]
Quick question:
Shouldn't this:
https://github.com/odow/SDDP.jl/blob/e3dcf54431fe97e8ca6537d724ac69cd2af22c60/src/plugins/stopping_rules.jl#L87

be instead  (assuming `sense = :Min`) :
`return sample_mean - sample_ci  <= current_bound` ?

Otherwise, when simulating the policy, the confidence interval may be too narrow, and the bound may skip the confidence interval entirely between simulation steps. I.e. the bound is below `sample_mean - sample_ci`, then you iterate some `iteration_periods`, the bound moves up, and the next time you simulate you are above `sample_mean + sample_ci`.

I agree that this should not happen if the bound is converging to the correct value, since it should be inside the CI at least 95% of the time for `z_score=1.96` but nevertheless I think one should stop when above the CI lower limit.

**Comment by odow** [comment]
In general, I try to avoid using this stopping rule. I prefer the one I outline in #178.

That said, feel free to make a pull request changing this to what you suggest (with the other way for maximization) and I'll add it.

**Comment by aferragu** [comment]
#178 certainly looks better and more promising. The problem with confidence intervals also is that you may have a large variance in the average cost, and hence the algorithm terminates too early because of the cost falling into the large CI (the opposite of what I was saying above). In that case the policy can still be improved.

Nevertheless, due to the monotonicity of the bound, I think it would be better to change it. I'll try to make the PR.
