### ISSUE TITLE
Scenario generation

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#208]
@lingquant has some interesting things in msppy: [code](https://github.com/lingquant/msppy), [paper](http://www.optimization-online.org/DB_FILE/2019/05/7199.pdf).

In particular:

 - [ ] tools to help scenario generation
    We could integrate things like https://github.com/JuliaStochOpt/Scenarios.jl
    I've discussed this with Bernardo P. as well, basically given the analytic form of a process, 
    automatically discretize and form a policy graph. msppy shows that it's very helpful for users (#216)
 - [x] plot bound over time
    It'd be nice to throw up an interactive HTML dashboard with callbacks
 - [ ] the ability to simulate a continuous stochastic process
    We can actually do that now we have sampling oracles. Just needs to be implemented
 - [x] an extensive form solver
    Much like StochDynamicProgramming.jl
 - [x] parallelization
    We really need to re-implement this
 - [x] this stopping rule: https://github.com/odow/SDDP.jl/issues/178#issuecomment-491992499

**Comment by frapac** [comment]
Scenario.jl should be tidy up to improve robustness. I have some ideas to improve the package, planning to open an issue soon. I found also this package, which seems to be quite relevant to use with SDDP: 
https://github.com/holgerteichgraeber/ClustForOpt.jl

Have you got any idea on how to re-implement the parallelization (e.g. implementing Pinto's method where parallelization occurs in the backward pass or keeping a set of forward/backward passes running independently from one other?)

**Comment by odow** [comment]
Cc @holgerteichgraeber. Is ClustForOpt.jl suitable for discretizing time series data into a Markov chain?

**Comment by odow** [comment]
> Have you got any idea on how to re-implement the parallelization

I'll probably just implement parallel forward/backward passes (#196). Parallelizing by node, or by RHS terms (#159) is more complicated.

**Comment by holgerteichgraeber** [comment]
> 
> 
> Cc @holgerteichgraeber. Is ClustForOpt.jl suitable for discretizing time series data into a Markov chain?

I think it would be possible. Would probably need an additional function to calculate transition probabilities, but that should be pretty simple. 

With ClustForOpt, you can take a time series of N time steps and divide it up into K* representative periods of length T each (N=K* \times T) (equivalent to scenarios in stochastic programming). You can then use the clustering methods to reduce it it K < K* periods. 

When you cluster and obtain K periods, the ClustData struct has a parameter `k_ids`. `k_ids` contains N ids that correspond to the cluster number that the original period is represented by. A function that walks through `k_ids` could calculate transition probabilities.

**Comment by odow** [comment]
@kirui93 has this package that we should look at incorporating: https://github.com/kirui93/ScenTrees.jl

At the very least, we should make use of https://github.com/kirui93/ScenTrees.jl/blob/100119ff76622c72a04dcaa72b83b50a4331edff/src/LatticeApprox.jl#L5-L47
