### ISSUE TITLE
Initial Markov State for every variable

### ISSUE THREAD

**Issue by barrykertesz** [odow/SDDP.jl#211]
Hello Oscar, in one older Issue (#152 ) I found this comment: _"Refactoring into policy graphs is a major re-write, so I have been putting it off. Introducing a parameter for the initial Markov state should be relatively straight forward."_ I was wondering if that parameter for the initial markov state is included in the SDDP. For example, taking as a reference the exemplary model for asset management, where we have the stock and the bond: is there a way to say that the bond begins with the markov state 1 and the stock with the markov state 2? So that in the second stage there will be the 2x2 matrix as in the stages 3 and 4. Thank you!

**Comment by odow** [comment]
There is a little bit to unpack here.

> if that parameter for the initial Markov state is included in the SDDP.

Yes, but it is poorly documented. There is 
https://odow.github.io/SDDP.jl/latest/tutorial/04_markov_uncertainty/
but it only describes how to construct a Markovian policy graph from a vector of transition matrices. 

That means if there are three stages, you would have to do something like
```Julia
SDDP.MarkovianPolicyGraph(
            transition_matrices = [
                [0.2 0.8],
                [0.4 0.6; 0.6 0.4],
                [0.4 0.6; 0.6 0.4]
            ]
        ) do subproblem, node
```

Another approach that isn't documented uses this
https://github.com/odow/SDDP.jl/blob/1d680ed3eb74b5a9a582b4ee86ea761bd7f80ffa/src/user_interface.jl#L255-L261

You can achieve the same graph as above with
```Julia
graph = SDDP.MarkovianGraph(
    stages = 3,
    transition_matrix = [0.4 0.6; 0.6 0.4],
    root_node_transition = [0.2 0.8]
)
SDDP.PolicyGraph(
        graph
        ) do subproblem, node
```

For the second part of your question: 

> is there a way to say that the bond begins with the markov state 1 and the stock with the markov state 2?

No. In the example, there are only two Markov states, and only one can be realized at a time. You could work around this by having a Markov process with four states `[(b1, s1), (b1, s2), (b2, s1), (b2, s2)]` and define an appropriate transition matrix. Then you could stay that to start in `b1` and `s2`, `root_node_transition = [0.0, 1.0, 0.0, 0.0]`.

**Comment by barrykertesz** [comment]
Thank you for your prompt support! As I see, the combination of the states start to get heavy once you get many assets and, let's say, 10 states.

**Comment by odow** [comment]
Yes. Things get very heavy quickly. Although solution time scales approximately linearly with the total number of nodes (Markov states * number of stages) in the graph.

The standard approach would be to use the Markov chain to represent market-states (bear, bull, etc), and then use stagewise-independent returns within each Markov state. That corresponds to making `Phi` depend on the Markov state in this example
https://github.com/odow/SDDP.jl/blob/1d680ed3eb74b5a9a582b4ee86ea761bd7f80ffa/examples/asset_management_stagewise.jl#L39-L42

If your prices/returns _only_ appear in the objective, you could consider using https://odow.github.io/SDDP.jl/latest/tutorial/14_objective_states/, but it too starts to slow once you get past a small number of states.

**Comment by barrykertesz** [comment]
Off course, that noise resource in the objective function would also be very helpful. Thank you very much, Oscar. Btw, your SDDP package is awesome!

**Comment by odow** [comment]
Leaving this open until the docs are improved.
