### ISSUE TITLE
BoundsError: attempt to access 0-element Array{SDDP.Log,1} at index [0]

### ISSUE THREAD

**Issue by peraaslid** [odow/SDDP.jl#231]
When I'm training a model I get a lot of warnings:
"Blank name detected for variable MathOptInterface.VariableIndex(31). Renamed to x31."
"Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(29). Renamed to c29."
After this it crashed with error:
"BoundsError: attempt to access 0-element Array{SDDP.Log,1} at index [0]"

I was able to reproduce this behaviour with the example "tiger_problem" using CPLEX as solver. Is this due to recent updates of SDDP.jl or MathOptInterface? Is there a simple workaround for it?

**Comment by odow** [comment]
Can you share the full error please? This looks pretty bad, so I'll take a look this morning.

**Comment by peraaslid** [comment]
Julia version: 1.1.0
Running "tiger_problem.jl" with CPLEX. CPLEX is doing some branch and cut, several iterations and then this comes. Anything else you need?
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(1). Renamed to x1.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(2). Renamed to x2.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(3). Renamed to x3.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(4). Renamed to x4.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(5). Renamed to x5.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(6). Renamed to x6.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(7). Renamed to x7.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(8). Renamed to x8.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(9). Renamed to x9.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(10). Renamed to x10.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(11). Renamed to x11.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(12). Renamed to x12.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(8). Renamed to c8.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(9). Renamed to c9.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(10). Renamed to c10.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(19). Renamed to c19.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(20). Renamed to c20.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(21). Renamed to c21.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(22). Renamed to c22.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(23). Renamed to c23.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(24). Renamed to c24.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(25). Renamed to c25.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(26). Renamed to c26.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(27). Renamed to c27.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(11). Renamed to c11.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(12). Renamed to c12.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(13). Renamed to c13.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(14). Renamed to c14.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(15). Renamed to c15.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(16). Renamed to c16.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(17). Renamed to c17.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(18). Renamed to c18.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}}(1). Renamed to c1.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}}(2). Renamed to c2.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}}(3). Renamed to c3.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}}(6). Renamed to c6.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}}(7). Renamed to c7.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}}(4). Renamed to c4.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}}(5). Renamed to c5.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(1). Renamed to x1.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(2). Renamed to x2.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(3). Renamed to x3.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(4). Renamed to x4.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(5). Renamed to x5.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(6). Renamed to x6.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(7). Renamed to x7.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(8). Renamed to x8.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(9). Renamed to x9.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(10). Renamed to x10.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(11). Renamed to x11.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for variable MathOptInterface.VariableIndex(12). Renamed to x12.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:95
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(8). Renamed to c8.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(9). Renamed to c9.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.EqualTo{Float64}}(10). Renamed to c10.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(19). Renamed to c19.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(20). Renamed to c20.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(21). Renamed to c21.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(22). Renamed to c22.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(23). Renamed to c23.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(24). Renamed to c24.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(25). Renamed to c25.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(26). Renamed to c26.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.GreaterThan{Float64}}(27). Renamed to c27.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(11). Renamed to c11.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(12). Renamed to c12.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(13). Renamed to c13.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(14). Renamed to c14.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(15). Renamed to c15.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(16). Renamed to c16.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(17). Renamed to c17.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.SingleVariable,MathOptInterface.LessThan{Float64}}(18). Renamed to c18.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}}(1). Renamed to c1.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}}(2). Renamed to c2.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}}(3). Renamed to c3.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}}(6). Renamed to c6.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}}(7). Renamed to c7.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}}(4). Renamed to c4.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
┌ Warning: Blank name detected for constraint MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}}(5). Renamed to c5.
└ @ MathOptFormat C:\Users\pera\.julia\packages\MathOptFormat\iRtuE\src\MathOptFormat.jl:54
ERROR: LoadError: BoundsError: attempt to access 0-element Array{SDDP.Log,1} at index [0]
Stacktrace:
 [1] getindex at .\array.jl:729 [inlined]
 [2] #train#36(::Int64, ::Nothing, ::Int64, ::String, ::Bool, ::Array{SDDP.AbstractStoppingRule,1}, ::SDDP.Expectation, ::SDDP.InSampleMonteCarlo, ::SDDP.CutType, ::Float64, ::Bool, ::Int64, ::Bool, ::typeof(SDDP.train), ::SDDP.PolicyGraph{Symbol}) at C:\Users\pera\.julia\packages\SDDP\GgtGq\sc\algorithm.jl:894
 [3] #train at .\none:0 [inlined]
 [4] tiger_problem() at ...

**Comment by peraaslid** [comment]
Thanks!! That was quick fix. Seems to be working fine again.
