### ISSUE TITLE
SMPS reader

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#241]
@gjharsha has C code for parsing SMPS here: https://github.com/USC3DLAB/SD/blob/master/src/smps.h
and has expressed interest in adding it to SDDP.jl.

There are two options
 - compiling and distributing a C library
 - re-writing in Julia

I'm not sure which requires less effort.

However, there are some licensing issues, because MPL 2.0 allows commercial use, but the SD license requires a commercial license from USC. So we might need to ask @gjharsha if he's willing to make the code (just `smps.h` and `smps.c`, not the full SD solver) available under a more permissive license.

**Comment by mtanneau** [comment]
Is this still topical?

I'm currently writing a pure-julia SMPS parser (actually, most of it is written I think, I'm mostly re-factoring the code and making it ready for public release).

Let me know if it would be relevant here.

**Comment by odow** [comment]
> Is this still topical?

Yes!!!

> I'm currently writing a pure-julia SMPS parser (actually, most of it is written I think, I'm mostly re-factoring the code and making it ready for public release).

💯👍 🚀 

Let me know what I can do to help!

**Comment by mtanneau** [comment]
What I need for myself (and for which I have most of the infrastructure) is to parse two-stage stochastic LPs from `SMPS` files. By `.smps` I mean `.cor`, `.sto` and `.tim` files.

I'm hoping the marginal cost of supporting more time periods and quadratic terms should be OK.

Things that would be useful to discuss would be:
* Data structures
* Supported formats and constraints (e.g. QPs)
* Some small instances for unit testing

So far I've only worked with the `tssp` instances that are shipped with the [PDCGM software](https://www.maths.ed.ac.uk/~gondzio/software/pdcgm.html), (see `data/tssp/` in the extracted folder).

**Comment by odow** [comment]
Two stage LPs only sounds good by me! No need to do multistage. Data structure is template matrices and vectors, and list of element changes for second stage problems, along with their probabilities. Keep it simple as possible.

**Comment by odow** [comment]
#332 implements a reader/writer for StochOptFormat. At this point, we should write a SMPS -> SOF converter. 

I have no interest in writing an SMPS writer.

**Comment by mtanneau** [comment]
Fine by me.

**Comment by odow** [comment]
Closing in favor of SMPSReader.
