### ISSUE TITLE
Recorded Simulate Variables

### ISSUE THREAD

**Issue by yakyak462** [odow/SDDP.jl#243]
Is there any way to save variables that don't show up in every stage when doing SDDP.simulate? In particular, I am interested in control variables that appear in the first stage, but not afterwards. Currently, I am getting the error

`ERROR: LoadError: No variable named var1 exists in the subproblem. If you want to simulate     the value of a variable, make sure it is defined in _all_ subproblems.`

The obvious workaround is define a bunch of first stage variables in all my other variables, but that seems possibly computationally inefficient.

**Comment by odow** [comment]
We could replace the error 
https://github.com/odow/SDDP.jl/blob/4e8ceda336554e4405dd74b4bce11c3577c5af63/src/algorithm.jl#L1054
with a `NaN`, or provide an option. I put the error to catch misspellings.
