### ISSUE TITLE
Out-of-sample simulation with objective states

### ISSUE THREAD

**Issue by adow031** [odow/SDDP.jl#251]
We're building some SDDP models that we wish to train using certain data and corresponding probabilities, and then simulate the performance out-of-sample.

Without objective states it would be possible to store the cuts and reload them into a different model (so long as the states are not changed); however, this is not supported with objective states.

We've tried first training the model, and then modifying the `term` within the `noise_terms` attribute of each `node`. However, these appear to a named tuple and cannot be modified.

![error1](https://user-images.githubusercontent.com/8185462/64331557-1ec46480-d027-11e9-8ec4-1a60d01763bd.png)

Is there a recommended / documented way that we should approach this?

Thanks.

**Comment by odow** [comment]
There is an example of using the `SDDP.Historical` sampling scheme at the bottom of https://odow.github.io/SDDP.jl/latest/tutorial/04_markov_uncertainty/

We should add an explicit tutorial on how to do out-of-sample simulations.

If you want to conduct an out-of-sample Monte Carlo simulation, then you will need to implement a new sampling scheme by creating a new `AbstractSamplingScheme` and implementing `sample_scenario`:
https://github.com/odow/SDDP.jl/blob/11530992d1091002b5a326e9af77acd76f240611/src/plugins/headers.jl#L30-L53

You could imagine an interface to supply the out-of-sample realizations as follows:
```Julia
struct OutOfSampleMonteCarlo{T}
    noise_terms::Dict{T, Vector{Noise}}
    children::Dict{T, Vector{Noise{T}}}
end

function OutOfSampleMonteCarlo(f::Function, graph::PolicyGraph{T}) where {T}
    noise_terms = Dict{T, Vector{Noise}}()
    children = Dict{T, Vector{Noise{T}}}()
    for key in keys(graph.nodes)
        noise, child = f(key)
        noise_terms[key] = noise
        children[key] = child
    end
    return OutOfSampleMonteCarlo{T}(noise_terms, children)
end

# Then, the user writes:
sampler = OutOfSampleMonteCarlo(graph) do node
    noise_terms = [SDDP.Noise(1, 0.3), SDDP.Noise(2, 0.7)]
    children = node < T ? [SDDP.Noise(node + 1, 1.0)] : SDDP.Noise{Int}[]
    return noise_terms, children
end
```
Then `sample_scenario` should be straight-forward to implement. You can borrow some of the functions from `InSampleMonteCarlo`:
https://github.com/odow/SDDP.jl/blob/11530992d1091002b5a326e9af77acd76f240611/src/plugins/sampling_schemes.jl#L26-L106

**Comment by adow031** [comment]
Thanks for this. The complexity of this is a little beyond where we are, with our Julia skills.

However, we hacked the following solution, applied to your Basic Tutorial III:
```julia
for t in 1:3
    for s in 1:3
        if s==1 || s==2
            p=0.5
        else
            p=0.0
        end
        model.nodes[t].noise_terms[s]=SDDP.Noise((inflow=s*1.0,fuel_multiplier=t*1.0),p)
    end
end
```
We can then run `simulate` as normal, and it will perform the out-of-sample simulation.

Of course this limits us in terms of the number of `noise_terms` possible (and destroys the original model), but it's easy to implement.

**Comment by odow** [comment]
I will try to get time to implement this. It's been on my list for a while and multiple people have asked.

**Comment by odow** [comment]
@adow031 this is now implemented. See https://odow.github.io/SDDP.jl/latest/guides/simulate_using_a_different_sampling_scheme for the documentation.
