### ISSUE TITLE
Add cut patterns to SDDiP

### ISSUE THREAD

**Issue by eltuck** [odow/SDDP.jl#257]
Thank y'all for all your work on SDDP and SDDiP packages. I've been been updating a model that previously used SDDiP.jl to SDDP.jl, and an initial draft seems to run fine. At this point, I have a couple questions:

* Is it possible to specify a cut pattern? (E.g., Pattern(integer_optimality = 1, strengthened_benders = 1)).
* Can I change the binary approximation precision?

I glanced through the src files but couldn't figure out what the options would be or if those are still features.

Thanks, again!

**Comment by lkapelevich** [comment]
I would try to start with infeasible duals so that Kelley' method has the chance to work toward a cut that is only "just valid". But I don't know how worthwhile it'll turn out practically.

**Comment by odow** [comment]
Closing in favor of #246
