### ISSUE TITLE
SDDiP doesn't respect tolerances

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#264]
The tolerances here should use the ones inside `SDDiP` instead of hard-coded `1e-8`:

https://github.com/odow/SDDP.jl/blob/951c5bf0ebc149c42465d37baee0189a84278c73/src/plugins/integrality_handlers.jl#L217

_Reported by Xian Yu, U. Mich._

**Comment by lkapelevich** [comment]
There should probably be an error/warning if the tolerances are too small, maybe `1e-6`, because if the gap isn't small enough the duals may be infeasible.

**Comment by odow** [comment]
Closing in favor of #246
