### ISSUE TITLE
Pkg> test SDDP fails

### ISSUE THREAD

**Issue by finmod** [odow/SDDP.jl#288]
Pkg> test SDDP fails as follows:
```Julia
Terminating training with status: iteration_limit
------------------------------------------------------------------
Test Summary:                            | Pass  Fail  Total
SDDP.jl                                  |  783     1    784
  Unit Tests                             |  709     1    710
    plugins/backward_sampling_schemes.jl |  203          203
    plugins/bellman_functions.jl         |   17           17
    plugins/integrality_handlers.jl      |  139          139
    plugins/risk_measures.jl             |   40           40
    plugins/sampling_schemes.jl          |   71           71
    plugins/stopping_rules.jl            |   17           17
    visualization/value_functions.jl     |   18           18
    visualization/visualization.jl       |    5            5
    algorithm.jl                         |   27           27
    binary_expansion.jl                  |   36           36
    deterministic_equivalent.jl          |   12     1     13
      cyclic checks                      |   10           10
      time_limit                         |          1      1
      objective_states                   |    1            1
      belief_states                      |    1            1
    modeling_aids.jl                     |   45           45
    user_interface.jl                    |   79           79
  Examples                               |   57           57
  Parallel                               |   17           17
ERROR: LoadError: Some tests did not pass: 783 passed, 1 failed, 0 errored, 0 broken.
in expression starting at C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\runtests.jl:20
ERROR: Package SDDP errored during testing
```

**Comment by odow** [comment]
Hi there, Can you post the full print out of the test that failed? I guess you're on Windows? Are all your packages up-to-date?

**Comment by finmod** [comment]
Here it is after Pkg > up and Pkg> build SDDP on Julia1.3.1
Building CodecZlib ─→ `C:\Users\Denis\.julia\packages\CodecZlib\5t9zO\deps\build.log`
  Building CodecBzip2 → `C:\Users\Denis\.julia\packages\CodecBzip2\T5yr7\deps\build.log`

(v1.3) pkg> test SDDP
   Testing SDDP
 Resolving package versions...
    Status `C:\Users\Denis\AppData\Local\Temp\jl_jhJk8n\Manifest.toml`
  [6e4b80f9] BenchmarkTools v0.4.3
  [b99e7846] BinaryProvider v0.5.8
  [00ebfdb7] CSTParser v0.6.2
  [49dc2e85] Calculus v0.5.1
  [523fee87] CodecBzip2 v0.6.0
  [944b1d66] CodecZlib v0.6.0
  [bbf7d656] CommonSubexpressions v0.2.0
  [864edb3b] DataStructures v0.17.7
  [163ba53b] DiffResults v1.0.2
  [b552c78f] DiffRules v1.0.0
  [f6369f11] ForwardDiff v0.10.8
  [60bf3e95] GLPK v0.12.1
  [cd3eb016] HTTP v0.8.8
  [83e8ac13] IniFile v0.5.0
  [682c06a0] JSON v0.21.0
  [7d188eb4] JSONSchema v0.1.1
  [4076af6c] JuMP v0.20.1
  [98e50ef6] JuliaFormatter v0.1.19
  [f4570300] MathOptFormat v0.4.0
  [b8f27783] MathOptInterface v0.9.7
  [739be429] MbedTLS v0.7.0
  [77ba4419] NaNMath v0.3.3
  [efe28fd5] OpenSpecFun_jll v0.5.3+1
  [bac558e1] OrderedCollections v1.1.0
  [69de0a69] Parsers v0.3.10
  [3cdcf5f2] RecipesBase v0.7.0
  [189a3867] Reexport v0.2.0
  [f4570300] SDDP v0.2.1
  [276daf66] SpecialFunctions v0.9.0
  [90137ffa] StaticArrays v0.12.1
  [a759f4b9] TimerOutputs v0.5.3
  [0796e94c] Tokenize v0.5.7
  [3bb67fe8] TranscodingStreams v0.9.5
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
┌ Warning: Radius is very small. You should probably use `SDDP.Expectation()` instead.
└ @ SDDP C:\Users\Denis\.julia\packages\SDDP\3B4BV\src\plugins\risk_measures.jl:275
Simulated policy value: [ 4.494910e+00,  6.705090e+00]
Simulated policy value: [ 4.218969e+00,  6.181031e+00]
Simulated policy value: [ 5.120828e+00,  7.279172e+00]
Simulated policy value: [ 4.494910e+00,  6.705090e+00]
Simulated policy value: [ 4.218969e+00,  6.181031e+00]
Simulated policy value: [ 5.120828e+00,  7.279172e+00]
┌ Warning: `SDDP.save` is deprecated. Use `SDDP.plot` instead.
│   caller = ip:0x0
└ @ Core :-1
time_limit: Test Failed at C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\deterministic_equivalent.jl:94
  Expression: SDDP.deterministic_equivalent(model, time_limit=0.0)
    Expected: ErrorException("Unable to formulate deterministic equivalent: Time limit exceeded!")
  No exception thrown
Stacktrace:
 [1] top-level scope at C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\deterministic_equivalent.jl:94
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Test\src\Test.jl:1107
 [3] top-level scope at C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\deterministic_equivalent.jl:86
┌ Warning: Budget for nodes is less than the number of stages. Using one node per stage.
└ @ SDDP C:\Users\Denis\.julia\packages\SDDP\3B4BV\src\modeling_aids.jl:87
┌ Warning: Too few scenarios to form an approximation of the lattice. Restarting the approximation with 1000 scenarios.
└ @ SDDP C:\Users\Denis\.julia\packages\SDDP\3B4BV\src\modeling_aids.jl:67
┌ Warning: Too few scenarios to form an approximation of the lattice. Restarting the approximation with 10000 scenarios.
└ @ SDDP C:\Users\Denis\.julia\packages\SDDP\3B4BV\src\modeling_aids.jl:67
Confidence_interval = 189.59 ± 14.64
------------------------------------------------------------------
                SDDP.jl (c) Oscar Dowson, 2017-19

Numerical stability report
  Non-zero Matrix range     [1e+00, 1e+00]
  Non-zero Objective range  [2e-01, 3e+00]
  Non-zero Bounds range     [5e+01, 5e+01]
  Non-zero RHS range        [0e+00, 0e+00]
No problems detected

Solver: serial mode

 Iteration    Simulation       Bound         Time (s)    Proc. ID
        1    0.000000e+00  -4.963160e+01   3.000021e-03          1
        2   -2.293160e+01  -4.680515e+01   3.600001e-02          1
        3   -2.356515e+01  -2.482867e+01   3.700018e-02          1
        4   -3.334867e+01  -2.396000e+01   3.900003e-02          1
        5   -2.396000e+01  -2.396000e+01   4.000020e-02          1
        6   -4.260000e+01  -2.396000e+01   4.200006e-02          1
        7   -2.396000e+01  -2.396000e+01   4.300022e-02          1
        8   -5.320000e+00  -2.396000e+01   4.400015e-02          1
        9   -2.396000e+01  -2.396000e+01   4.500008e-02          1
       10   -2.396000e+01  -2.396000e+01   4.700017e-02          1

Terminating training with status: iteration_limit
------------------------------------------------------------------
 ─────────────────────────────────────────────────────────────────────────────
                                      Time                   Allocations
                              ──────────────────────   ───────────────────────
       Tot / % measured:           722ms / 1.13%           20.2MiB / 3.82%

 Section              ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────────────
 backward_pass            10   4.12ms  50.5%   412μs    359KiB  45.5%  35.9KiB
   solve_subproblem       40   1.97ms  24.2%  49.3μs    206KiB  26.1%  5.16KiB
 forward_pass             10   3.42ms  41.9%   342μs    369KiB  46.8%  36.9KiB
   solve_subproblem       30   2.79ms  34.2%  93.1μs    312KiB  39.5%  10.4KiB
   sample_scenario        10    153μs  1.88%  15.3μs   10.0KiB  1.27%  1.00KiB
 calculate_bound          10    619μs  7.59%  61.9μs   61.1KiB  7.74%  6.11KiB
 ─────────────────────────────────────────────────────────────────────────────
------------------------------------------------------------------
                SDDP.jl (c) Oscar Dowson, 2017-19

Numerical stability report
  Non-zero Matrix range     [1e+00, 1e+00]
  Non-zero Objective range  [2e-01, 3e+00]
  Non-zero Bounds range     [5e+01, 5e+01]
  Non-zero RHS range        [0e+00, 0e+00]
No problems detected

Solver: serial mode

 Iteration    Simulation       Bound         Time (s)    Proc. ID
        1    0.000000e+00  -4.963160e+01   0.000000e+00          1
        2   -4.291601e+00  -4.680515e+01   0.000000e+00          1
        3   -1.424515e+01  -2.482867e+01   0.000000e+00          1
        4   -6.188670e+00  -2.396000e+01   0.000000e+00          1
        5   -2.396000e+01  -2.396000e+01   0.000000e+00          1
        6   -2.396000e+01  -2.396000e+01   0.000000e+00          1
        7   -4.260000e+01  -2.396000e+01   1.500010e-02          1
        8   -4.260000e+01  -2.396000e+01   1.500010e-02          1
        9   -5.320000e+00  -2.396000e+01   1.500010e-02          1
       10   -2.396000e+01  -2.396000e+01   1.500010e-02          1

Terminating training with status: iteration_limit
------------------------------------------------------------------
 ─────────────────────────────────────────────────────────────────────────────
                                      Time                   Allocations
                              ──────────────────────   ───────────────────────
       Tot / % measured:          19.1ms / 34.7%           0.97MiB / 79.7%

 Section              ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────────────
 backward_pass            10   3.43ms  51.7%   343μs    359KiB  45.5%  35.9KiB
   solve_subproblem       40   1.85ms  27.9%  46.2μs    206KiB  26.1%  5.16KiB
 forward_pass             10   2.68ms  40.5%   268μs    369KiB  46.8%  36.9KiB
   solve_subproblem       30   2.23ms  33.7%  74.4μs    312KiB  39.5%  10.4KiB
   sample_scenario        10    124μs  1.87%  12.4μs   10.0KiB  1.27%  1.00KiB
 calculate_bound          10    519μs  7.83%  51.9μs   61.1KiB  7.74%  6.11KiB
 ─────────────────────────────────────────────────────────────────────────────
Confidence_interval = 122.17 ± 13.61
Confidence_interval = 117.08 ± 12.32
┌ Warning: The addition operator has been used on JuMP expressions a large number of times. This warning is safe to ignore but may indicate that model generation is slower than necessary. For performance reasons, you should not add expressions in a loop. Instead of x += y, use add_to_expression!(x,y) to modify x in place. If y is a single variable, you may also use add_to_expression!(x, coef, y) for x += coef*y.
└ @ JuMP C:\Users\Denis\.julia\packages\JuMP\MsUSY\src\JuMP.jl:747
Activating new environment at `C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\Project.toml`
      From worker 3:    Activating new environment at `C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\Project.toml`
      From worker 5:    Activating new environment at `C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\Project.toml`
      From worker 4:    Activating new environment at `C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\Project.toml`
      From worker 2:    Activating new environment at `C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\Project.toml`
------------------------------------------------------------------
                SDDP.jl (c) Oscar Dowson, 2017-19

Numerical stability report
  Non-zero Matrix range     [0e+00, 0e+00]
  Non-zero Objective range  [1e+00, 1e+00]
  Non-zero Bounds range     [1e+00, 6e+00]
  Non-zero RHS range        [0e+00, 0e+00]
No problems detected

Solver: Asynchronous mode with 4 workers.

 Iteration    Simulation       Bound         Time (s)    Proc. ID
        1    9.000000e+00   6.000000e+00   5.451600e+01          3
        2    3.000000e+00   6.000000e+00   5.453700e+01          3
        3    5.000000e+00   6.000000e+00   5.453900e+01          3
        4    3.000000e+00   6.000000e+00   5.454600e+01          3
        5    7.000000e+00   6.000000e+00   5.454900e+01          3
        6    7.000000e+00   6.000000e+00   5.455200e+01          3
        7    9.000000e+00   6.000000e+00   5.456000e+01          3
        8    7.000000e+00   6.000000e+00   5.456300e+01          3
        9    5.000000e+00   6.000000e+00   5.456500e+01          3
       10    5.000000e+00   6.000000e+00   5.456800e+01          3
       11    7.000000e+00   6.000000e+00   5.457200e+01          3
       12    7.000000e+00   6.000000e+00   5.457400e+01          3
       13    3.000000e+00   6.000000e+00   5.457500e+01          3
       14    3.000000e+00   6.000000e+00   5.457600e+01          3
       15    7.000000e+00   6.000000e+00   5.457900e+01          3
       16    7.000000e+00   6.000000e+00   5.458200e+01          3
       17    5.000000e+00   6.000000e+00   5.458500e+01          3
       18    9.000000e+00   6.000000e+00   5.458900e+01          3
       19    5.000000e+00   6.000000e+00   5.459000e+01          3
       20    5.000000e+00   6.000000e+00   5.459100e+01          3

Terminating training with status: iteration_limit
------------------------------------------------------------------
------------------------------------------------------------------
                SDDP.jl (c) Oscar Dowson, 2017-19

Numerical stability report
  Non-zero Matrix range     [1e+00, 1e+00]
  Non-zero Objective range  [1e+00, 1e+00]
  Non-zero Bounds range     [1e+00, 6e+00]
  Non-zero RHS range        [4e+00, 4e+00]
No problems detected

Solver: Asynchronous mode with 4 workers.

 Iteration    Simulation       Bound         Time (s)    Proc. ID
        1    7.000000e+00   6.000000e+00   7.799983e-02          1
        2    3.000000e+00   6.000000e+00   9.299994e-02          1
        3    7.000000e+00   6.000000e+00   9.299994e-02          1
        4    7.000000e+00   6.000000e+00   9.299994e-02          1
        5    7.000000e+00   6.000000e+00   9.299994e-02          1
        6    7.000000e+00   6.000000e+00   9.299994e-02          1
        7    7.000000e+00   6.000000e+00   9.299994e-02          1
        8    9.000000e+00   6.000000e+00   9.299994e-02          1
        9    7.000000e+00   6.000000e+00   9.299994e-02          1
       10    3.000000e+00   6.000000e+00   1.090000e-01          1
       11    9.000000e+00   6.000000e+00   1.090000e-01          1
       12    5.000000e+00   6.000000e+00   1.090000e-01          1
       13    7.000000e+00   6.000000e+00   1.090000e-01          1
       14    3.000000e+00   6.000000e+00   1.090000e-01          1
       15    5.000000e+00   6.000000e+00   1.090000e-01          1
       16    9.000000e+00   6.000000e+00   1.090000e-01          1
       17    7.000000e+00   6.000000e+00   1.090000e-01          1
       18    7.000000e+00   6.000000e+00   1.250000e-01          1
       19    9.000000e+00   6.000000e+00   1.250000e-01          1
       20    7.000000e+00   6.000000e+00   1.250000e-01          1

Terminating training with status: iteration_limit
------------------------------------------------------------------
Test Summary:                            | Pass  Fail  Total
SDDP.jl                                  |  782     1    783
  Unit Tests                             |  708     1    709
    plugins/backward_sampling_schemes.jl |  203          203
    plugins/bellman_functions.jl         |   17           17
    plugins/integrality_handlers.jl      |  139          139
    plugins/risk_measures.jl             |   40           40
    plugins/sampling_schemes.jl          |   70           70
    plugins/stopping_rules.jl            |   17           17
    visualization/value_functions.jl     |   18           18
    visualization/visualization.jl       |    5            5
    algorithm.jl                         |   27           27
    binary_expansion.jl                  |   36           36
    deterministic_equivalent.jl          |   12     1     13
      cyclic checks                      |   10           10
      time_limit                         |          1      1
      objective_states                   |    1            1
      belief_states                      |    1            1
    modeling_aids.jl                     |   45           45
    user_interface.jl                    |   79           79
  Examples                               |   57           57
  Parallel                               |   17           17
ERROR: LoadError: Some tests did not pass: 782 passed, 1 failed, 0 errored, 0 broken.
in expression starting at C:\Users\Denis\.julia\packages\SDDP\3B4BV\test\runtests.jl:20
ERROR: Package SDDP errored during testing

**Comment by odow** [comment]
Ha. You're machine is too fast to hit the timelimit. I should make the example harder to construct or use a negative time limit in the test.

This isn't an issue with the correctness of the code on your machine.
