### ISSUE TITLE
Multi-dimensional random variable in the objective function

### ISSUE THREAD

**Issue by marykh162** [odow/SDDP.jl#311]
I have a question about the following piece of code for multi-dimensional noise term in the objective function.
```julia
SDDP.parameterize(subproblem, support, probability) do ω
    JuMP.fix(x.out, ω.value)
    @stageobjective(subproblem, ω.coefficient * x.out)
    println("ω is: ", ω)
end
```
I do not understand why this line is needed: `JuMP.fix(x.out, ω.value)`.

In addition, my model contains the same random variables in the RHS (both in the objective function and the RHS). Could you let me know how I should force the model to use the same scenario in the constraints? 

I appreciate your help.

**Comment by odow** [comment]
`fix(x, value)` will set the lower and upper bounds on `x` to `value`, so that `value <= x <= value`. It's just an example.

To use the same realization in the RHS and in the objective, use:
```Julia
@constraint(subproblem, my_con, x.in + x.out == 0)
SDDP.parameterize(subproblem, [1, 2, 3]) do ω
    set_normalized_rhs(my_con, ω)
    @stageobjective(subproblem, ω * x.out)
end
```
This will ensure that the realization of `ω` used for the RHS is the same as the realization used in the objective.

**Comment by marykh162** [comment]
> 
> 
> `fix(x, value)` will set the lower and upper bounds on `x` to `value`, so that `value <= x <= value`. It's just an example.
> 
> To use the same realization in the RHS and in the objective, use:
> 
> ```julia
> @constraint(subproblem, my_con, x.in + x.out == 0)
> SDDP.parameterize(subproblem, [1, 2, 3]) do ω
>     set_normalized_rhs(my_con, ω)
>     @stageobjective(subproblem, ω * x.out)
> end
> ```
> 
> This will ensure that the realization of `ω` used for the RHS is the same as the realization used in the objective.

Thank you so much! Could you please take a look at part of my code as follows:
include("PACFD.jl")           
support1 = [(EC = a1, transfer = b1, direct = c1, ICU = d1) for a1 in qe1 for b1 in qt1 for c1 in qd1 for d1 in qi1]
probability1 = [pec1 * ptr1 * pdi1 * piu1 for pec1 in pe1 for ptr1 in pt1 for pdi1 in pd1 for piu1 in pi1]
		   SDDP.parameterize(sp, support1, probability1) do ω
		   @stageobjective(sp, cr[1]*(ω.EC-v[1]) + cr[2]*(ω.transfer-v[2])+cr[3]*(ω.direct-v[3])+cr[4]*(ω.ICU-v[4]))
		   @constraint(sp, v[1] <= ω.EC)
		   @constraint(sp, v[2] <= ω.transfer)
		   @constraint(sp, v[3] <= ω.direct)
		   @constraint(sp, v[4] <= ω.ICU)
		   end
Does this look correct to you?
Thanks!

**Comment by odow** [comment]
Instead of `@constraint(sp, v[1] <= ω.EC)` use `set_upper_bound(v[1], ω.EC)`.

The `@constraint` way will keep all constraints as they are added, which is why you're probably thinking it isn't working.

**Comment by marykh162** [comment]
> 
> 
> Instead of `@constraint(sp, v[1] <= ω.EC)` use `set_upper_bound(v[1], ω.EC)`.
> 
> The `@constraint` way will keep all constraints as they are added, which is why you're probably thinking it isn't working.

Thanks! I appreciate your help.

**Comment by odow** [comment]
No worries. Let me know how you get on.

**Comment by odow** [comment]
Closing this because it seems to be resolved. Please re-open if that isn't the case.

**Comment by marykh162** [comment]
> 
> 
> Closing this because it seems to be resolved. Please re-open if that isn't the case.

Yes, it works. Thank you so much!
