### ISSUE TITLE
state variable

### ISSUE THREAD

**Issue by Esnilg** [odow/SDDP.jl#314]
Hello,

I hope you are well. I ask you how I can access the value of a state variable from previous periods (not just the previous one). Example:

F.out = F.in + x.new - "x.old[t-lifetime]" + remainder.

where t is the period, and lifetime is the lifetime of the power plant. F is the total capacity, x.new is the new capacity installed and x.old is the capacity of period 1 or 2 or 3.

**Comment by odow** [comment]
You need to expand the state space, and then add linking constraints, e.g., if `t` is the number of periods in the past:
```Julia
@variable(sp, x[t=0:2], SDDP.State, initial_value = 0)
@constraint(sp, [t=0:1], x[t].in == x[t + 1].out)
@constraint(sp, x[0].out >= x[0].in + x[1].in + x[2].in)
```

**Comment by Esnilg** [comment]
Thank you very much Oscar
Excuse me, but I meant that "t" is the stage. That is, if I have 4 stages and if I am in stage 3, how to obtain the value of the variable in stage N-2 or N-1. Same as you explain it in the previous answer?
example my code

@constraint(sp, retirements[i = Symbol.(TECHNOLOGIES)], Retirements[i] == (t > lifetime_[i] ? F_Mult[i,t-lifetime_[i]].in : 0.0) + (Capacidad_residual[i][t] - Capacidad_residual[i][t+1]));

**Comment by Esnilg** [comment]
But it is the real situation. Suppose that in state 1 the model decides to invest in 2 GW of WIND. And then in state 2 he decides to invest 3 more GW of WIND. So suppose this technology (WIND) has a lifetime of 2 states. It means that state 3 I have to remove 2 GW of capacity from WIND and state 4 I have to remove 3 GW of capacity from WIND. The equation I am using is:

WIND_TOTAL.out = WIND_TOTAL.in + WIND - WIND [t-2], if t> 2

I would like to know how to make this equation possible.

**Comment by odow** [comment]
It helps to clearly define your state and control variables. If the problem in stage `t` depends on a decision in a previous stage, that decision is a state variable. For more, see [Wiley [Paywall]](https://onlinelibrary.wiley.com/doi/abs/10.1002/net.21932) or 
[Preprint](http://www.optimization-online.org/DB_HTML/2018/11/6914.html).

I think you're after something like:
```Julia
@variable(sp, WIND_TOTAL >= 0, SDDP.State, initial_value = 0)
@variable(sp, WIND[1:3] >= 0, SDDP.State, initial_value = 0)
@variable(sp, wind_invest_now >= 0)
@constraint(sp, WIND_TOTAL.out == WIND_TOTAL.in + wind_invest_now - WIND_INVEST[3].in)
@constraint(sp, WIND[1].out == wind_invest_now)
@constraint(sp, WIND[2].out == WIND[1].in)
@constraint(sp, WIND[3].out == WIND[2].in)
```
