### ISSUE TITLE
A distributionally-robust risk measure based on the Wasserstein distance.

### ISSUE THREAD

**Issue by Esnilg** [odow/SDDP.jl#315]
Dear Odow

I hope you are well, I am writing again because I am reviewing how the DRO is used with the Wassertein distance.

I did a test with the same function that you use as an example

risk_measure = SDDP.Wasserstein(
        GLPK.Optimizer; alpha=0.5) do x, y
   return abs(x - y)
end

but running training gives me an error.

Iteration    Simulation       Bound         Time (s)    Proc. ID   # Solves
ERROR: LoadError: MethodError: no method matching -(::SDDP.Noise{NamedTuple{(:p1, :p2, :p3, :p4, :p5, :p6, :p7),NTuple{7,Float64}}}, ::SDDP.Noise{NamedTuple{(:p1, :p2, :p3, :p4, :p5, :p6, :p7),NTuple{7,Float64}}})
Closest candidates are:
  -(::Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}}, ::T) where T at C:\Users\esnil\.julia\packages\MathOptInterface\RmalA\src\Utilities\functions.jl:1125
  -(::T, ::Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}}) where T at C:\Users\esnil\.julia\packages\MathOptInterface\RmalA\src\Utilities\functions.jl:1131

I have 7 uncertain parameters with 3 values ​​each. If you can explain what I'm doing wrong.

Best regards

**Comment by odow** [comment]
```Julia
SDDP.Wassterstein(GLPK.Optimizer; alpha = 0.5) do x, y
    return abs(x -y)
end
```
is equivalent to
```Julia
function foo(x, y)
    return abs(x -y)
end
SDDP.Wassterstein(foo, GLPK.Optimizer; alpha = 0.5)
```

The function `foo` should return a norm between two supports `x` and `y` (i.e., \omega_1 and \omega_2). Since it seems like your supports are named tuples, you might want, for example,
 the 2-norm between them:
```Julia
function foo(x, y)
    return sqrt(
        (x.p1 - y.p1)^2 +
        (x.p2 - y.p2)^2 +
        (x.p3 - y.p3)^2 +
        (x.p4 - y.p4)^2 +
        (x.p5 - y.p5)^2 +
        (x.p6 - y.p6)^2 +
        (x.p7 - y.p7)^2
    )
end
```

**Comment by Esnilg** [comment]
Hi

Try again with what it tells me, but now it gives me another different error

 Iteration    Simulation       Bound         Time (s)    Proc. ID   # Solves
ERROR: LoadError: type Noise has no field p1

The definition of the support is as follows

supports = [(p1=a1, p2=a2, p3=a3, p4=a4, p5=a5, p6=a6, p7=a7) for a1 in M_end_uses_input[:ELECTRICITY,t] for a2 in M_end_uses_input[:LIGHTING,t] for a3 in M_end_uses_input[:HEAT_HIGH_T,t] for a4 in M_end_uses_input[:HEAT_LOW_T_SH,t]  for a5 in M_end_uses_input[:HEAT_LOW_T_HW,t]  for a6 in M_end_uses_input[:MOBILITY_PASSENGER,t] for a7 in M_end_uses_input[:MOBILITY_FREIGHT,t]]

Thanks

**Comment by odow** [comment]
I guess I meant 
```Julia
(x.term.p1 - y.term.p2)^2
```
and so on.

**Comment by Esnilg** [comment]
Now it works thank you very much
