### ISSUE TITLE
Add cut selection for objective and belief states

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#326]
Opening an issue because this feature is noticeably absent.

**Comment by odow** [comment]
@adow031 says: https://github.com/odow/SDDP.jl/issues/324#issuecomment-646384093

> I've previously done manual cut selection on objective state models, where I discard cuts that no longer bind for any visited states, but that was in the Julia 0.6 version.

Did you just do a level-one type thing? Or did you solve the out-of-band LP to determine binding?

**Comment by adow031** [comment]
We were essentially applying level-one cut selection, but applied it outside of the SDDP and reloaded the cuts. An LP was required to determine binding constraints. With higher dimensions for the objective state, there are more possible active constraints for each point.
