### ISSUE TITLE
how parallelize the simulations

### ISSUE THREAD

**Issue by Esnilg** [odow/SDDP.jl#342]
Hi,

Hello,

I hope you are fine, I am trying to parallelize the simulations but it gives me an error that model is not defined

```julia
ERROR: On worker 2:
UndefVarError: model not defined
```

How can I make it in all processes. I don't want to use the asynchronous version because it consumes a lot of ram memory and then I can't clean it.
```julia
@everywhere function simulacion(i)
    simulations0 = SDDP.simulate(model, 1);
    return sum(simulations0[1][t][:stage_objective] for t in 1:nb_periods)
end

salida = pmap(simulacion, 1:10)
```
best regards

**Comment by odow** [comment]
> I don't want to use the asynchronous version because it consumes a lot of ram memory and then I can't clean it.

What do you mean by "I can't clean it"? 

Unfortunately, anything we do is going to use a lot of RAM because we initialize a full model on each processor.

**Comment by odow** [comment]
Is it the training or the simulating the consumes the RAM and you can't clean?

i.e. what happens if you train serially and simulate async. And vice versa.

**Comment by Esnilg** [comment]
Hi Oscar

I always use SDDP.train without asynchronous. but when I use SDDP.simulate to simulate 3000 times serially this takes about 7-8 hours. So I have tried to use asynchronous but it is saturating the ram memory

When I use SDDP.train in a multi-cut form, the RAM memory always stays at 34% of use, and then when I SDDP.simulate with asynchronously, the percentage of RAM memory use goes up to 51%, but after it ends it stays, and if i re-simulate asynchronously the percentage goes up more and stays after simulation ends, I use GC.gc () to release garbage but nothing.

**Comment by odow** [comment]
> when I use SDDP.simulate to simulate 3000 times serially this takes about 7-8 hours

Wow. This should definitely not happen.

Can you send me the model (oscar.dowson at northwestern.edu)? I will have a look.

**Comment by Esnilg** [comment]
The model is great! Discretize the cost of operating natural gas since it follows a stochastic process such as a three-state markov chain, I also have 14 uncertain parameters (demand, cost) and I use 20 samples for uncertain parameters. I do not understand where I can send the model

**Comment by odow** [comment]
> I do not understand where I can send the model

Email it to me oscar.dowson@northwestern.edu
