### ISSUE TITLE
Can you use MC homogenies and non-homogenies? 

### ISSUE THREAD

**Issue by Esnilg** [odow/SDDP.jl#350]
Hello Oscar

I wanted to write to ask you where I can read in your code how you generate the forward paths when you use a markov chain (MC). Can you use MC homogenies and non-homogenies?

My doubt is that if I have 5 states, but it turns out that the probabilities of [1] -> [1,2,3,4,5] are [0.0, 0.4,0.0,0.0,0.6], which follows to determine the next state

Thank you

**Comment by odow** [comment]
@Esnilg here you go: 
https://github.com/odow/SDDP.jl/blob/ed19aea3985213db67fd795549ad22a05d356746/src/plugins/sampling_schemes.jl#L222-L284

In your example, the `InSampleMonteCarlo` should only sample states 2 and 5.

**Comment by odow** [comment]
Closing as stale, and I don't think there is anything actionable to do here.
