### ISSUE TITLE
Use SDDP.jl to solve a simple routine economics problem.

### ISSUE THREAD

**Issue by azev77** [odow/SDDP.jl#351]
Hi and thank you for this package!

How can I use this package to solve a very routine dynamic programming problem economists usually solve with value function iteration? 
Here is the problem (which happens to have a simple closed form solution, so we can check)
<img width="342" alt="image" src="https://user-images.githubusercontent.com/7883904/98152038-17a11c80-1e9f-11eb-99f4-fe9e200290db.png">

Using optimization terminology:
state variable: k
action variable: c
reward function: log(c)

**Comment by odow** [comment]
I suggest you start with the tutorials: https://odow.github.io/SDDP.jl/latest/#Tutorials

You will probably have some difficulty with numerical issues associated with the `log` function. SDDP is generally better suited for linear problems with better numerics.

**Comment by odow** [comment]
Closing since this isn't an issue that needs resolving in SDDP.jl.
