### ISSUE TITLE
No output shown if dashboard is true, if running SDDP.train a 2nd time

### ISSUE THREAD

**Issue by adow031** [odow/SDDP.jl#352]
I have a model that I was training with dashboard = true, and the first time I run SDDP.train, it will load up a browser and visually show the progress. However, if I try training either the same model or another model in the same Julia session it will load up a new browser tab, but neither show progress visually, nor in the REPL - the training also doesn't end.

I was able to reproduce this issue using the simple_hydro_thermal.jl model, by changing line 91 to:
```Julia
SDDP.train(model, iteration_limit = 100, dashboard=true)
```

This isn't really a big deal, since I was just testing out the dashboard, but I had throught I'd broken the model somehow.

**Comment by odow** [comment]
Yeah. I think I encountered this before. The dashboard is very much experimental, which is why it's off by default.
