### ISSUE TITLE
issue with transition matrix in SDDP.MarkovianPolicyGraph

### ISSUE THREAD

**Issue by lorenzoreus** [odow/SDDP.jl#353]
Hi,

I have the following error,  "Probability on edges leaving node (8, 23) sum to 1.0000000000000002, but this must be in [0.0, 1.0]"

I think I understand the error but I don't know how to fix it. It is the numerical precision when defining the transition matrix. For example, the following probability vector does not sum up  1.0, but 0.9999999999999998 instead. 

N=4
prob_b=0.9
a=(1/2^N)*ones(2^N,1)
prob=vcat(prob_b*a,(1-prob_b)*a)
println(prob)
print(sum(prob))

How can I define a transition matrix that is accepted by the SDDP.MarkovianPolicyGraph function. my code works with  other transition matrices. I even try to add (substract) the difference in the last component of the vector (to force the sum =1)  but still gives me the same mistake

Thanks for any help!

Lorenzo

**Comment by odow** [comment]
We should probably just relax this line:
https://github.com/odow/SDDP.jl/blob/ed19aea3985213db67fd795549ad22a05d356746/src/user_interface.jl#L74

**Comment by lorenzoreus** [comment]
Hi Oscar,

Thank you so much for your fast response. What I should do to update the changed you made in the user_interface? I run Pkg.update(“SDDP”) but I still have the issue. O r should I wait until you upload a new version of the whole package?

Sorry for my ignorance

Lorenzo



On 15-11-2020, at 20:07, Oscar Dowson <notifications@github.com<mailto:notifications@github.com>> wrote:



We should probably just relax this line:
https://github.com/odow/SDDP.jl/blob/ed19aea3985213db67fd795549ad22a05d356746/src/user_interface.jl#L74

**Comment by odow** [comment]
Try `] add SDDP#odow-patch-1`. I'm out for the afternoon. I'll try to remember to make a proper release when I get back to my computer. Please ping me if I don't do it in a day or so.

**Comment by odow** [comment]
@lorenzoreus should be fixed once this tag is merged: https://github.com/JuliaRegistries/General/pull/24837

#355 turned out to be more work than I expected.

**Comment by lorenzoreus** [comment]
Works like a charm!! Thank you for the effort. 

Lorenzo
