### ISSUE TITLE
read_cuts_from_file does not load cuts into the BellmanFunction

### ISSUE THREAD

**Issue by vitorlppf** [odow/SDDP.jl#360]
Greetings,

While trying to visualize the value function of a model after reading cuts I had saved, I found out that was not possible. That is because `SDDP.read_cuts_from_file` doesn't add `SDDP.Cut` objects to the model's cut oracles. Training the model again whenever one wants to visualize the value function seems excessive.

I believe this could be solved in three different ways:
1. After calling `SDDP._add_cut`, create a `SDDP.Cut` object and `push!` it into the node's cut oracle. Functional, but inelegant because it repeats the process performed inside `SDDP._add_cut`;
2. Change `SDDP._add_cut` (or one of the functions called by it) so that it does the aforementioned process when reading cuts from file. It shouldn't break anything, as long as care is taken to avoid adding the same cut twice to the cut oracle;
3. Set `cut_selection = true` in the argument of `SDDP._add_cut` call inside `SDDP.read_cuts_from_file`. After testing proposed solution 1 and showing it to a professor, he made this suggestion. I tested it and it does add the cuts to the cut oracles. However, a comment in the function reads as follows:
    > `# Importantly, don't run cut selection when adding these cuts.`
    
    This leads me to believe you have a reason for not doing so, which I'm unaware of.

As mentioned above, I have tested 1 and 3 by creating functions outside of this module's scope and executing them. With my current setup, I can't create a branch of my local installation of SDDP and execute it. However, I could edit the local installation in a different machine and make a pull request, should you believe it to be necessary (although I personally see these changes as either minor or derived directly from your own code).

Thanks,
Vitor.

**Comment by odow** [comment]
The reason for not running cut selection was that when loading cuts into a new model, we don't have a collection of points in the state-space at which to evaluate the cuts.

It might be possible to modify 
https://github.com/odow/SDDP.jl/blob/687883afc2afd6e3ee220c200f3c80b5605bbf3a/src/plugins/bellman_functions.jl#L70-L72
to
```julia
    if cut_selection
        _cut_selection_update(V, cut, xᵏ)
    else
        push!(V.cut_oracle.cuts, cut)
    end
```
but you would have to test to see if anything breaks. I don't know if there is an edge case.

**Comment by odow** [comment]
The blocker for this is that if we read cuts into the Bellman object, we don't have any corresponding list of states at which to check the heights against. So we probably need a way to add cuts with a `keep = true` flag so we don't just immediately throw them out again.

**Comment by adow031** [comment]
Sorry; I didn’t see this issue when I posted mine.

The easiest thing to do may be to create a loaded_cuts object within the bellman_function so that you don’t have to loop through these cuts during the cut selection.

Or you could include the states in the cut json file, then it should all just work automatically.

Tony

**Comment by odow** [comment]
Yeah adding the states to the JSON file is a good option. It seems like you'd almost always want that. It might make the file quite large though.

**Comment by adow031** [comment]
You could add a zip / unzip step for the json files, since they should be quite compressible.
________________________________

**Comment by adow031** [comment]
Thanks for your explanation of this issue. I've made some changes to your `read_` and `write_` function. According to the license, I'm meant to provide these to you. Given it's just a hack for my needs, I'll just paste my updated functions below:

```julia
function write_cuts_to_file(model::SDDP.PolicyGraph{T},
    filename::String,
    include_state::Bool = true) where {T}

    cuts = Dict{String,Any}[]
    for (node_name, node) in model.nodes
        if node.objective_state !== nothing || node.belief_state !== nothing
            error(
                "Unable to write cuts to file because model contains " *
                "objective states or belief states.",
            )
        end
        node_cuts = Dict(
            "node" => string(node_name),
            "single_cuts" => Dict{String,Any}[],
            "multi_cuts" => Dict{String,Any}[],
            "risk_set_cuts" => Vector{Float64}[],
        )

        if include_state
            for i in 1:length(node.bellman_function.global_theta.cut_oracle.cuts)
                cut = node.bellman_function.global_theta.cut_oracle.cuts[i]
                state = node.bellman_function.global_theta.cut_oracle.states[i]
                push!(
                    node_cuts["single_cuts"],
                    Dict(
                        "intercept" => cut.intercept,
                        "coefficients" => copy(cut.coefficients),
                        "state" => copy(state.state)
                    ),
                )
            end
        else
            for i in 1:length(node.bellman_function.global_theta.cut_oracle.cuts)
                cut = node.bellman_function.global_theta.cut_oracle.cuts[i]
                push!(
                    node_cuts["single_cuts"],
                    Dict(
                        "intercept" => cut.intercept,
                        "coefficients" => copy(cut.coefficients),
                    ),
                )
            end
        end
        for (i, theta) in enumerate(node.bellman_function.local_thetas)
            for cut in theta.cut_oracle.cuts
                push!(
                    node_cuts["multi_cuts"],
                    Dict(
                        "realization" => i,
                        "intercept" => cut.intercept,
                        "coefficients" => copy(cut.coefficients),
                    ),
                )
            end
        end
        for p in node.bellman_function.risk_set_cuts
            push!(node_cuts["risk_set_cuts"], p)
        end
        push!(cuts, node_cuts)
    end
    open(filename, "w") do io
        return write(io, JSON.json(cuts))
    end
    return
end
```

```julia
function read_cuts_from_file(
    model::SDDP.PolicyGraph{T},
    filename::String;
    node_name_parser::Function = _node_name_parser,
) where {T}
    # So the cuts are written to file after they have been normalized
    # to `θᴳ ≥ [θᵏ - ⟨πᵏ, xᵏ⟩] + ⟨πᵏ, x′⟩`. Thus, we pass `xᵏ=0` so that
    # eveything works out okay.
    # Importantly, don't run cut selection when adding these cuts.
    cuts = JSON.parsefile(filename, use_mmap = false)
    for node_cuts in cuts
        node_name = node_name_parser(T, node_cuts["node"])::T
        node = model[node_name]
        bf = node.bellman_function
        # Loop through and add the single-cuts.
        for json_cut in node_cuts["single_cuts"]
            coefficients = Dict{Symbol,Float64}(
                Symbol(k) => v for (k, v) in json_cut["coefficients"]
            )
            cs = false
            if haskey(json_cut,"state")
                state = Dict{Symbol,Float64}(
                    Symbol(k) => v for (k, v) in json_cut["state"]
                )
                cs = true
            else
                state = Dict(key => 0.0 for key in keys(coefficients))
            end

            _add_cut(
                bf.global_theta,
                json_cut["intercept"],
                coefficients,
                state,
                nothing,
                nothing;
                cut_selection = cs,
            )
        end
        # Loop through and add the multi-cuts. There are two parts:
        #  (i) the cuts w.r.t. the state variable x
        # (ii) the cuts that define the risk set
        # There is one additional complication: if these cuts are being read
        # into a new model, the local theta variables may not exist yet.
        if length(node_cuts["risk_set_cuts"]) > 0
            _add_locals_if_necessary(
                node,
                bf,
                length(first(node_cuts["risk_set_cuts"])),
            )
        end
        for json_cut in node_cuts["multi_cuts"]
            coefficients = Dict{Symbol,Float64}(
                Symbol(k) => v for (k, v) in json_cut["coefficients"]
            )
            _add_cut(
                bf.local_thetas[json_cut["realization"]],
                json_cut["intercept"],
                coefficients,
                Dict(key => 0.0 for key in keys(coefficients)),
                nothing,
                nothing;
                cut_selection = false,
            )
        end
        # Here is part (ii): adding the constraints that define the risk-set
        # representation of the risk measure.
        for json_cut in node_cuts["risk_set_cuts"]
            expr = @expression(
                node.subproblem,
                bf.global_theta.theta - sum(
                    p * V.theta for (p, V) in zip(json_cut, bf.local_thetas)
                )
            )
            if JuMP.objective_sense(node.subproblem) == MOI.MIN_SENSE
                @constraint(node.subproblem, expr >= 0)
            else
                @constraint(node.subproblem, expr <= 0)
            end
        end
    end
    return
end
```

I set up the read function so that it is backward-compatiable with previous cut files.

**Comment by odow** [comment]
Ah nice. I think this is a good solution.

**Comment by adow031** [comment]
I hadn't realised that the `θᵏ` in the `_add_cut` function was being modified.

If doesn't seem efficient to add `πᵏ[key] * xᵏ[key]` onto the intercept, only to subtract it again.

I think that

```julia
for (key, x) in xᵏ
    θᵏ -= πᵏ[key] * xᵏ[key]
end
```
shouldn't be in the `_add_cut` function since this is a conversion of the intercept that could be done prior.

(Another option would be to create a different `_add_cut` functions for loading cuts.)

**Comment by odow** [comment]
I'm not worried about the extra cost. It's effectively negligible in the grand scheme of things. It's simpler for the `_add_cut` function to expect `theta >= intercept + coefficients' * (x - state)`. I guess the alternative is to change `write_to_file` to that format, instead of the one we currently have which is `theta >= intercept + coefficients' * x`.
