### ISSUE TITLE
Add noise in the constraint matrix, in a vector

### ISSUE THREAD

**Issue by lorenzoreus** [odow/SDDP.jl#368]
Hi, 
Is it possible to create a constraint with a vector of noises (coefficients) multiplied to a variable vector? I know how to do this with one coefficient and one variable using the JuMP.set_normalized_coefficient. But I can't adapt it to two coefficients two variable, for example 

b[1]*x[1]+b[2]*x[2]<=3 where b is the noise and x the variable. 

Thank you very much. 
Lorenzo

 use the or

**Comment by odow** [comment]
I guess you want something like this:
```Julia
@constraint(sp, c, 1.0 * x[1] + 1.0 * x[2] <= 3)

B = [
    [1.0, 2.0],
    [2.0, 1.0],
]
SDDP.parameterize(sp, B) do b
    for i = 1:length(b)
        set_normalized_coefficient(c, x[i], b[i])
    end
end
```

**Comment by lorenzoreus** [comment]
Works perfectly!
Thank you very much

**Comment by odow** [comment]
No worries.
