### ISSUE TITLE
Reusing the Gurobi environment

### ISSUE THREAD

**Issue by aferragu** [odow/SDDP.jl#377]
Oscar:

Is there a way to initalize the Gurobi optimizer in `SDDP.jl` in a way that reuses the Gurobi environment (à la JuMP)?

I mean, in JuMP you can do:
```julia
gurobi_env = Gurobi.Env()
model = JuMP.Model(optimizer_with_attributes(() -> Gurobi.Optimizer(gurobi_env), "OutputFlag" => 0))
```
This avoids the nasty output from Gurobi telling you when your license expires each time you create a subproblem, which can be cumbersome in large models.

Thanks!

**Comment by odow** [comment]
Yes. See 
https://github.com/odow/SDDP.jl/blob/6819d06f5a05f2004ff6556f837aca9516bebdc3/examples/paper_models/ddb_2018.jl#L22-L25

**Comment by aferragu** [comment]
Ok so:
```julia
optimizer = optimizer_with_attributes(() -> Gurobi.Optimizer(gurobi_env), "OutputFlag" => 0)
```
does the trick and suppresses Gurobi output. Great! I think I tried something like that but didn't work the first time, hence my question.

I'm trying to prepare some teaching materials based on your library and these fixes really improve the jupyter notebooks. Thanks again!

**Comment by odow** [comment]
> I'm trying to prepare some teaching materials based on your library 

Nice! You might be interested in these
* https://odow.github.io/SDDP.jl/stable/tutorial/21_theory_intro/
* https://odow.github.io/SDDP.jl/stable/tutorial/22_risk/

Please open an issue if you have suggestions for how to improve.
