### ISSUE TITLE
Can I have the max function in the objective cost function?

### ISSUE THREAD

**Issue by hssharadga** [odow/SDDP.jl#378]
Thank you for sharing your work.

Does this library support a min-max problem? In other words, Can I have the max function in the objective function which I try to minimize:

Is the SDDP able to solve this kind of problem?

For example the objective function: obj = energy (1,t) * 10 if t<H
.........................................................................obj = energy (1,t) * 10 + max (energy(1,1:t)) if t=H

**Comment by odow** [comment]
Ah. I may have mis-read this question.

**Comment by odow** [comment]
You're looking for https://docs.mosek.com/modeling-cookbook/linear.html#maximum. So something like
```Julia
using SDDP
model = SDDP.LinearPolicyGraph(
    stages = 3,
    sense = :Min,
    lower_bound = 0.0,
) do sp, t
    @variable(model, energy_max, SDDP.State, initial_value = 0)
    @variable(model, energy)
    @constraint(model, energy_max.out >= energy_max.in)
    @constraint(model, energy_max.out >= energy)
    if t < 3
        @stageobjective(model, 10 * energy)
    else
        @stageobjective(model, 10 * energy + energy_max.out)
    end
end
```

**Comment by hssharadga** [comment]
Thank you so much!
