### ISSUE TITLE
Incorporate the information from parent node in subproblems

### ISSUE THREAD

**Issue by Moon1193** [odow/SDDP.jl#389]
Hi Oscar,
We are modelling the optimization for a hydroelectric cascade system, one of the constraints is a dynamic equation which includes information from parent node and child node of scenario tree.

We want to incorporate the variable release[parent_node]( release of the last stage) instead of release[current_node] shown below (release of the the current stage) in each subproblem, but don't know a way to do that. We would be grateful if you could give us some suggestions on how to solve this problem.

![image](https://user-images.githubusercontent.com/60937356/112686860-dac8c880-8e33-11eb-8188-249a9a0b217f.png)

Please let me know if you need code to reproduce, so I can send it via email.
Thanks,

**Comment by odow** [comment]
Add "release" as a state variable.

See https://odow.github.io/SDDP.jl/stable/tutorial/01_first_steps/#Control-variables

![image](https://user-images.githubusercontent.com/8177701/112701081-846f8e80-8ef4-11eb-95dd-6e9ff3cf0cbb.png)

**Comment by odow** [comment]
Did this help? If you have follow-up questions, ask away. Otherwise I will close.

**Comment by Moon1193** [comment]
This worked. Thank you for your suggestion.

**Comment by odow** [comment]
Great!
