### ISSUE TITLE
First iteration takes a loooong time

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#390]
@jd-lara has an example like this:
```
Problem
  Nodes           : 2278
  State variables : 86
  Scenarios       : 7.93614e+45
  Solver          : serial mode

 Iteration    Simulation       Bound         Time (s)    Proc. ID   # Solves
        1    1.792142e+06   0.000000e+00   5.752572e+01          1       2302
        2    9.821713e+05   0.000000e+00   6.240440e+01          1       4604
        3    1.962243e+04   0.000000e+00   6.551834e+01          1       6906
        4    4.183718e+04   2.374731e+01   7.016413e+01          1       9208
```
The first iteration takes 57 seconds(!) then each subsequent iteration takes <5seconds.

We should profile to work out where this time is being spent.

**Comment by odow** [comment]
It's because of this: 
https://github.com/odow/SDDP.jl/blob/1201fa310f3472f4ca10bad089d843be27f7ff73/src/algorithm.jl#L819-L820

**Comment by odow** [comment]
We should add documentation on how to make big models faster.

**Comment by jd-lara** [comment]
@odow looks like this wasn't the reason for the delay 

```
                      SDDP.jl (c) Oscar Dowson, 2017-21

Problem
  Nodes           : 2278
  State variables : 98
  Scenarios       : 7.93614e+45
  Solver          : serial mode

 Iteration    Simulation       Bound         Time (s)    Proc. ID   # Solves
        1    1.751529e+06   0.000000e+00   5.403590e+01          1       2302
        2    1.014905e+06   0.000000e+00   5.960352e+01          1       4604
        3    6.233979e+04   0.000000e+00   6.272977e+01          1       6906

**Comment by odow** [comment]
Hmm. I wonder if it is https://github.com/odow/SDDP.jl/blob/9cdeed8de2f8e2d864771f30fd873a7c5c9642b0/src/algorithm.jl#L51-L76
I don't think I really expected 2278 nodes.

**Comment by jd-lara** [comment]
I like the ```it's just a one-off hit so let's optimize later```

**Comment by odow** [comment]
Confirmed. I'll make a PR.

**Comment by odow** [comment]
I literally remember writing this comment and thinking. Man, I should do this differently, but I had so many other things on my TODO list (https://github.com/odow/SDDP.jl/pull/180).

**Comment by odow** [comment]
I might actually just close this. Ideally the defaults are fast, and you don't have to use magic options when the model gets fast.
