### ISSUE TITLE
Adding uncertainty on the objective function

### ISSUE THREAD

**Issue by bonnkleiford** [odow/SDDP.jl#391]
Hello!

I would like to ask for a little help/clarification on adding uncertainty on the objective function.

In the tutorial/documentation, it only shows an example if the uncertainty is correlated with the uncertainty in the constraints. What if it is not? Like my uncertainty in the constraints is DEMAND, and for the obj function are PRICES?

Here is my current code:

```Julia
model = SDDP.LinearPolicyGraph(
    stages = T,
    sense = :Min,
    lower_bound = 0.0,
    optimizer = GLPK.Optimizer
) do subproblem, t
    # Define the state variable.
    @variable(subproblem,
        0 <= X[i = 1:I], 
        SDDP.State, initial_value = 0)
    
    # Define the control variables.
    @variables(subproblem, begin
        0 <= u[j=1:J]
        0 <= v[i=1:I, j=1:J, k=1:K]
        0 <= w[j=1:J]
        0 <= x[i=1:I]
        alpha[i=1:I] == alpha_0[i]
        beta[j=1:J] == beta_0[j]
        demand[j=1:J] == d_0[j]
    end) 
    
    @constraints(subproblem, begin
        [i=1:I], X[i].out == X[i].in + x[i]
        [i=1:I], sum(sum(a[i,j,k]*v[i,j,k] for k in 1:K) for j in 1:J) <= c[i]*X[i].out
        [j=1:J], w[j] + u[j] >= demand[j]
        [j=1:J,k=1:K], sum(v[i,j,k] for i in 1:I) >= w[j]
        end)
    
    @stageobjective(subproblem, sum(x[i]*alpha[i] for i in 1:I) + sum(u[j]*beta[j] for j in 1:J)) 
    if t != 1
        r = (t-1) % 4 == 0 ? 4 : (t - 1) % 4
        SDDP.parameterize(subproblem, 1:length(D[1][1][r])) do ω
            for j in 1:J
                JuMP.fix(demand[j] , D[ω][j][r])
                JuMP.fix(beta[j] , B[ω][j][r])
            end
            for i in 1:I
                JuMP.fix(alpha[i] , A[ω][i][r])
            end
        end
    end
end
```

I would be very happy to receive some help.

Thank you!

BIKEY

**Comment by odow** [comment]
See https://odow.github.io/SDDP.jl/stable/guides/add_multidimensional_noise_Terms/

Add the `@stageobjective` in `parameterize`. `u[j] * beta[j]` if `u` and `beta` are both variables is bilinear (non-convex). Gurobi is clever enough to reformulate this, but GLPK will throw an error.

**Comment by bonnkleiford** [comment]
Well, x[i] and u[j] are both decision variables and alpha[i] and beta[j] are there coefficients in the objective function. But, both alpha[i] and beta[j] are taken from this:

`
# INPUT
T = 4
I = 10
J = 10
K = 2
S = 100

alpha_0 =  [686, 784, 540, 641, 1073, 1388, 1727, 1469, 586, 515]
beta_0 = [174, 115, 92, 116, 93, 164, 190, 174, 190, 200]
d_0 = [607,943,732,1279,434,378,1964,430, 410, 525]

d_perturb =  [0.0422902245, 0.0549456137, 0.0868569685, 0.0950609064, 0.0538731273, 0.0917075818, 0.0673065114, 0.0594680277, 0.0544299191, 0.0782010312]
beta_perturb =  [0.0129739644, 0.063853852, 0.0925580104, 0.0766634092, 0.0953244752, 0.0563760149, 0.075759652, 0.0583249427, 0.0324810132, 0.0694020021]
alpha_perturb =  [0.0638533975, 0.068050401, 0.0747693903, 0.0514849591, 0.0323470258, 0.0480910211, 0.0304004586, 0.0976094813, 0.0694752024, 0.0703992735, 0.0775236862]

D = [[[round(LinearAlgebra.dot(rand(Normal(1, d_perturb[j])),d_0[j])) for s in 1:S] for j in 1:J] for t in 1:T]
A = [[[round(LinearAlgebra.dot(rand(Normal(1, alpha_perturb[j])),alpha_0[j])) for s in 1:S] for j in 1:I] for t in 1:T]
B = [[[round(LinearAlgebra.dot(rand(Normal(1, beta_perturb[j])),beta_0[j])) for s in 1:S] for j in 1:J] for t in 1:T]
`

I still find it a little confusing, but I will try.

**Comment by odow** [comment]
> I still find it a little confusing

If you have two independent random variables, form a new random variable from the Cartesian product of the the two.

```
A_support = [:a1, :a2]
a_probability = [0.2, 0.8]

B_support = [:b1, :b2]
B_probability = [0.5, 0.5]

C_support = [(a, b) for a in A_support for b in b_support]
C_probability = [a * b for a in A_probability for b in b_probability]
```

**Comment by bonnkleiford** [comment]
Thank you. Thank you.

It's getting a little bit clearer but also difficult since both my random variables are multi-dimensional.

**Comment by odow** [comment]
> both my random variables are multi-dimensional.

Nothing changes. Unless each element of each vector is independent???

```Julia
julia> A_support = [rand(2), rand(2)]
2-element Vector{Vector{Float64}}:
 [0.6737524204864189, 0.9446781815908085]
 [0.5690565871335029, 0.42455189783644576]

julia> A_probability = [0.2, 0.8]
2-element Vector{Float64}:
 0.2
 0.8

julia> B_support = [rand(3), rand(3)]
2-element Vector{Vector{Float64}}:
 [0.23162784872325437, 0.09530925195244921, 0.8809522780299612]
 [0.38846765215620027, 0.05908095768240562, 0.019024860488368933]

julia> B_probability = [0.5, 0.5]
2-element Vector{Float64}:
 0.5
 0.5

julia> C_support = [(a, b) for a in A_support for b in B_support]
4-element Vector{Tuple{Vector{Float64}, Vector{Float64}}}:
 ([0.6737524204864189, 0.9446781815908085], [0.23162784872325437, 0.09530925195244921, 0.8809522780299612])
 ([0.6737524204864189, 0.9446781815908085], [0.38846765215620027, 0.05908095768240562, 0.019024860488368933])
 ([0.5690565871335029, 0.42455189783644576], [0.23162784872325437, 0.09530925195244921, 0.8809522780299612])
 ([0.5690565871335029, 0.42455189783644576], [0.38846765215620027, 0.05908095768240562, 0.019024860488368933])

julia> C_probability = [a * b for a in A_probability for b in B_probability]
4-element Vector{Float64}:
 0.1
 0.1
 0.4
 0.4
```

**Comment by bonnkleiford** [comment]
Hi, Dr Oscar! Thank you so much for the help. I'm really trying it but I can't figure out something wrong I have been doing:

`
A_support = [[[round(LinearAlgebra.dot(rand(Normal(1, alpha_perturb[j])),alpha_0[j])) for s in 1:S] for j in 1:I] for t in 1:T]
A_probability = = [[[1/length(A[1][1]) for s in 1:S] for j in 1:J] for t in 1:T]

B_support = [[[round(LinearAlgebra.dot(rand(Normal(1, beta_perturb[j])),beta_0[j])) for s in 1:S] for j in 1:J] for t in 1:T]
B_probability = = [[[1/length(A[1][1]) for s in 1:S] for j in 1:J] for t in 1:T]

C = [(a,b) for a in A for b in B]
C_probability = [a*b for a in a_probability for b in b_probability]
`

I'm still getting some error.

PS
I also tried the way you handled it on the milkPOWDER model with @rhsnoises, but I think this was for the old version of SDDP.jl? I tried to implement it on another SDDP solver. :)

**Comment by odow** [comment]
I think you just need something like:
```Julia
_generate(x_perturb, x_0, i) = round(Int, x_0[i] * rand(Normal(1, x_perturb[i])))
support = map(1:T) do t
    return map(1:S) do s
        return (
            D = map(j -> _generate(d_perturb, d_0, j), 1:J),
            A = map(i -> _generate(alpha_perturb, alpha_0, i), 1:I),
            B = map(j -> _generate(beta_perturb, beta_0, j), 1:J),
        )
    end
end

SDDP.parameterize(subproblem, support[t]) do ω
    @stageobjective(subproblem, ω.A' * x + ω.B' * u)
    JuMP.fix.(demand , ω.D)
end
```

**Comment by bonnkleiford** [comment]
Oh, wow. That is amazing!

It totally worked!

Thank you very very much! :o

**Comment by odow** [comment]
No problem. Say hi to Nils.

**Comment by bonnkleiford** [comment]
I will. Thank you very much, again! :)

**Comment by odow** [comment]
You've defined `PRICE` as a variable, so even though you called `fix` the solver still sees it as decision variable. This is different to what happens in something like Pyomo.

Remove the `PRICE` variable and just use:
```julia
SDDP.parameterize(subproblem, [6,6,7,7,8,8,9,9,10,10]) do ω
    @stageobjective(subproblem, ω * sell_0)
end
```

**Comment by bonnkleiford** [comment]
Ahh I see. Thanks. I have been using the technique - calling RandomVariables as DecisionVariables on other problems and they work just fine. Hmmm. Thanks for this.

Now, I have one other question. I'm trying to model the same problem above but apparently, it is not possible to equate one StateVariable (`storage_0`) with another StateVariable (`storage_i[i]`) like

` storage_0.out = storage_i[i].in `

JuMP will provide this error:
`setfield! immutable struct of type State cannot be changed`

If instead I make it
` storage_0.out == storage_i[i].in `

it provides a solution but not exactly right. Maybe you have had a particularly encountered the same problem before. Thanks.

**Comment by odow** [comment]
You need to add it as a constraint 
```Julia
@constraint(sp, storage_0.out == storage_i[i].in)
```
