### ISSUE TITLE
 The realization is not one of the expected scenarios

### ISSUE THREAD

**Issue by hssharadga** [odow/SDDP.jl#395]
Hi!
I need to know if this tool supports my problem:

My question: what if I want to find the optimal solution and the realization is not one of the expected scenarios? Is this tool support this kind of problem or it has a limitation?
Your help is appreciated!

**Comment by odow** [comment]
Out-of-sample simulations are supported. If you have a particular realization you want to simulate, use: https://odow.github.io/SDDP.jl/stable/guides/simulate_using_a_different_sampling_scheme/#Historical-simulation

If you have out-of-sample distributions, use: https://odow.github.io/SDDP.jl/stable/guides/simulate_using_a_different_sampling_scheme/#Out-of-sample-Monte-Carlo-simulation

**Comment by odow** [comment]
Closing since there isn't anything to do here. Please re-open if you have a specific question of how to use the library.
