### ISSUE TITLE
Unable to access water values in multi storage SDDP calculation

### ISSUE THREAD

**Issue by csaiedu** [odow/SDDP.jl#398]
I am trying a few of your examples in the package SDDP.jl (which is great by the way), but I can't seem to find a way to extract the water values in the multi reservoir problem:

https://github.com/odow/SDDP.jl/blob/master/examples/msppy_hydro_thermal.jl

I tried with something like 
V = SDDP.ValueFunction(model[1])
cost, price = SDDP.evaluate(V,Symbol("storedEnergy[1]")=80000)

Also is there a way to do a spaghetti plot of each zone water values?

thanks for your help

**Comment by odow** [comment]
You need to use this method:
https://github.com/odow/SDDP.jl/blob/a77d27fb56b3dc46f46b8623cdd049935c8a549a/src/visualization/value_functions.jl#L160-L172
It's a bit hidden because it's only documented in the API Reference:
https://odow.github.io/SDDP.jl/stable/apireference/#SDDP.evaluate
We should improve that.

I haven't tried, but something like the following should work:
```Julia
x = Dict(
    Symbol("storedEnergy[1]") => 80_000.0,
)
SDDP.evaluate(V, x)
```

**Comment by csaiedu** [comment]
Using  x = Dict(Symbol("storedEnergy[1]") => 80_000.0)cost, price = SDDP.evaluate(V;x) I am getting MethodError: no method matching AbstractFloat(::Dict{Symbol, Float64})Closest candidates are:  (::Type{T})(!Matched::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50  (::Type{T})(!Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243  (::Type{T})(!Matched::Complex) where T<:Real at complex.jl:37  ...float(x::Dict{Symbol, Float64}) at float.jl:206(::SDDP.var"#224#225")(::Pair{Symbol, Dict{Symbol, Float64}}) at none:0iterate at generator.jl:47 [inlined]_all(f::Base.var"#282#284", itr::Base.Generator{Base.Iterators.Pairs{Symbol, Dict{Symbol, Float64}, Tuple{Symbol}, NamedTuple{(:x,), Tuple{Dict{Symbol, Float64}}}}, SDDP.var"#224#225"}, #unused#::Colon) at reduce.jl:922all(f::Function, itr::Base.Generator{Base.Iterators.Pairs{Symbol, Dict{Symbol, Float64}, Tuple{Symbol}, NamedTuple{(:x,), Tuple{Dict{Symbol, Float64}}}}, SDDP.var"#224#225"}) at reduce.jl:918Dict(kv::Base.Generator{Base.Iterators.Pairs{Symbol, Dict{Symbol, Float64}, Tuple{Symbol}, NamedTuple{(:x,), Tuple{Dict{Symbol, Float64}}}}, SDDP.var"#224#225"}) at dict.jl:131evaluate(V::SDDP.ValueFunction{Nothing, Nothing}; kwargs::Base.Iterators.Pairs{Symbol, Dict{Symbol, Float64}, Tuple{Symbol}, NamedTuple{(:x,), Tuple{Dict{Symbol, Float64}}}}) at value_functions.jl:216(::SDDP.var"#evaluate##kw")(::NamedTuple{(:x,), Tuple{Dict{Symbol, Float64}}}, ::typeof(SDDP.evaluate), V::SDDP.ValueFunction{Nothing, Nothing}) at value_functions.jl:216top-level scope at SDDP_Best_learning_4_reservoir.jl:154eval at boot.jl:360 [inlined] From: Oscar DowsonSent: 28 April 2021 22:16To: odow/SDDP.jlCc: csaiedu; AuthorSubject: Re: [odow/SDDP.jl] Unable to access water values in multi storage SDDP calculation (#398) You need to use this method:https://github.com/odow/SDDP.jl/blob/a77d27fb56b3dc46f46b8623cdd049935c8a549a/src/visualization/value_functions.jl#L160-L172It's a bit hidden because it's only documented in the API Reference:https://odow.github.io/SDDP.jl/stable/apireference/#SDDP.evaluateWe should improve that.I haven't tried, but something like the following should work:x = Dict(    Symbol("storedEnergy[1]") => 80_000.0,)SDDP.evaluate(V, x)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by csaiedu** [comment]
My bad it’s working indeed x = Dict(  Symbol("storedEnergy[1]") => 80_000.0,            Symbol("storedEnergy[2]") => 10_000.0,              Symbol("storedEnergy[3]") => 20_000.0,            Symbol("storedEnergy[4]") => 10_000.0)         cost, price = SDDP.evaluate(V,x)  Thank you for your help Kind regards From: Oscar DowsonSent: 28 April 2021 22:16To: odow/SDDP.jlCc: csaiedu; AuthorSubject: Re: [odow/SDDP.jl] Unable to access water values in multi storage SDDP calculation (#398) You need to use this method:https://github.com/odow/SDDP.jl/blob/a77d27fb56b3dc46f46b8623cdd049935c8a549a/src/visualization/value_functions.jl#L160-L172It's a bit hidden because it's only documented in the API Reference:https://odow.github.io/SDDP.jl/stable/apireference/#SDDP.evaluateWe should improve that.I haven't tried, but something like the following should work:x = Dict(    Symbol("storedEnergy[1]") => 80_000.0,)SDDP.evaluate(V, x)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by odow** [comment]
Looks like your email formatting got messed up. But I assume `My bad it’s working indeed` means it worked. I'll leave this issue open to remind me to improve the documentation.
