### ISSUE TITLE
MathOptFormat for SDDP.jl

### ISSUE THREAD

**Issue by bonnkleiford** [odow/SDDP.jl#399]
Hi again, Oscar!

I would like to ask if it is possible "print" the model we create through SDDP.jl or get a JSON file like the MathOptFormat file? I have tried to look for some example [code] which does this but I suppose it is not possible?

Thank you!

**Comment by odow** [comment]
You remind me that I need to get back around to finishing https://odow.github.io/StochOptFormat/. (Tell Nils I haven't forgotten, but I lost access to my Northwestern emails, so I don't have that thread anymore.)

https://odow.github.io/SDDP.jl/latest/apireference/#StochOptFormat
https://odow.github.io/SDDP.jl/latest/apireference/#Base.write-Tuple{IO,SDDP.PolicyGraph}

cc @joaquimg

**Comment by bonnkleiford** [comment]
Oh, now worries. Hehe. I will tell him.

Anyway, sorry, I'm still a bit lost. If I already created a problem (model) on SDDP.jl, how may I write/print it into a JSON format (as StochOptFormat or MathOptFormat)? Which function should I use? hehe.

Thanks, Oscar!

**Comment by bonnkleiford** [comment]
Oh, okay, I got it. 

Thank you!
