### ISSUE TITLE
The relationship of state variable in SDDP 

### ISSUE THREAD

**Issue by BYS-NCEPU** [odow/SDDP.jl#405]
Hi, Oscar!
    Recently, I try to use the SDDP with Julia environment. However, some relationship of state variable have bothered me. 
Firstly, can the initial value of state variable be understood as the state output of root node?(i.e., State.out of root node)
Secondly, is the state input of previous moment  equal to the next moment by default?(i.e., State[t-1].out==State[t].in)
Thanks in advance!

**Comment by odow** [comment]
> can the initial value of state variable be understood as the state output of root node?

Yes.

>  is the state input of previous moment equal to the next moment by default?

Yes.

Here are some links for further reading:

 - https://odow.github.io/SDDP.jl/stable/tutorial/01_first_steps/
 - https://odow.github.io/SDDP.jl/stable/tutorial/21_theory_intro/
 - https://pubsonline.informs.org/doi/10.1287/ijoc.2020.0987
 - https://doi.org/10.1002/net.21932

**Comment by odow** [comment]
If you can suggest improvements to the documentation, please let me know. Otherwise I'll close this issue.

**Comment by odow** [comment]
Closing. Please re-open if you have further questions.
