### ISSUE TITLE
Gap computation

### ISSUE THREAD

**Issue by bonnkleiford** [odow/SDDP.jl#424]
Hi, Oscar!

I wanted to ask if there is a function to get the gap between the `Simulation` and `Bound` (Upper and Lower bound) embedded in SDDP.jl?

Thank you!

**Comment by odow** [comment]
No. Note that `Simulation` is not the upper bound. It's just one simulation of the policy.

You can either compute it at the end of the training:
https://github.com/odow/SDDP.jl/blob/f3e34489cd85f38c759023af783e5baf3eda9808/docs/src/examples/biobjective_hydro.jl#L59-L64

Or you could add a statistical stopping rule with `verbose = true` which will print the gap
https://odow.github.io/SDDP.jl/stable/guides/choose_a_stopping_rule/#SDDP.Statistical

Something like 
```Julia
stopping_rules = [
    Statistical(
        num_replications = 1_000, 
        iteration_period = 10,
        verbose = true,
    ),
]
```
which will do a simulation of 1000 replications every 10 iterations and print the bound.

**Comment by odow** [comment]
If you just want the singular simulations, you can use https://odow.github.io/SDDP.jl/stable/apireference/#SDDP.write_log_to_csv to the log.

**Comment by odow** [comment]
There is no function for the upper bound. You would need to manually do the simulation like the `biobjective_hydro` example.

**Comment by bonnkleiford** [comment]
Okay. I see. I was able to do it by exporting it as a CSV then putting it as a DataFrame. 

Thank you!
