### ISSUE TITLE
Objective state with state-dependent Ω

### ISSUE THREAD

**Issue by lorenzoreus** [odow/SDDP.jl#444]
In the example,  
https://odow.github.io/SDDP.jl/stable/tutorial/advanced/11_objective_states/, is it possible to define an Ω that depends on a state variable (or objective state). Or if we can  create a probability vector "p" in SDDP.parameterize(subproblem, Ω, p) do ω that changes depending on a state variable (or objective state). I'm thinking in mean reverting processes, where the probability of going up(or down) changes depending on the same process. 

Thank you!

**Comment by odow** [comment]
> is it possible to define an Ω that depends

Doesn't matter the context, the Ω cannot depend on _anything_ other than the node index.

> I'm thinking in mean reverting processes,

Why do you need to modify Ω for this? Just add a mean reversion term (`-weight * (y_{t-1} - mean)`) to the process? The white-noise/innovation/random error term is independent of `y`.

**Comment by odow** [comment]
Closing since this is not possible and will never be possible. You can model mean-reverting processes with the state-space expansion trick.

**Comment by lorenzoreus** [comment]
I understand ,
thank you!
