### ISSUE TITLE
Fix docs of historical sampling scheme

### ISSUE THREAD

**Issue by franciscogaluppo** [odow/SDDP.jl#446]
Hi, this might be an obvious question, but how can I evaluate a model on out-of-sample scenarios? My main objective is to perform a "cross-validation" over an entire set of scenarios.

I'm building a hydropower dispatch model with multiple hydro plants (uncertain inflows) and a demand (uncertain too). To test on the in-sample scenarios I can just use Simulate with Historical sampling, specifying which scenarios to use. Can I use something similar but for out-of-sample scenarios?

The only thing I could find was this [example](https://odow.github.io/SDDP.jl/stable/tutorial/theory/21_theory_intro/#Implementation:-evaluating-the-policy), where its said that "The random variable can be out-of-sample, i.e., it doesn't have to be in the vector Ω we created when defining the model!", but I can't see how it generalizes.

Is there a way to do this?

Thank you!

**Comment by odow** [comment]
Documentation: https://odow.github.io/SDDP.jl/stable/guides/simulate_using_a_different_sampling_scheme/

**Comment by odow** [comment]
Ah. Perhaps the documentation isn't clear around the Historical: it doesn't have to be historical in-sample realizations. the values can be anything, provided they are the same type as the in-sample values.

**Comment by franciscogaluppo** [comment]
That's great! Thanks for the answer.

**Comment by franciscogaluppo** [comment]
Hi again. I've tried using the Historical sampling method, but I couldn't understand the docs. It is said "You can also pass a vector of scenarios, which are sampled sequentially:" and the exemple that follows:

```julia
SDDP.Historical([
           [(1, 1.0), (2, 2.0), (3, 3.0)],
           [(1, 1.1), (2, 2.1), (3, 3.1)],
           [(1, 1.2), (2, 2.2), (3, 3.2)]
       ])
```

But what are these numbers? I guessed that the first one is the stage and that the second one is the uncertain value. But, if that's the case, then it doesn't make sense since the model has two uncertain variables (inflow and fuel_multiplier). How is this assigning values to both of them?

Another example uses the Ω NamedTuple:

```julia
simulations = SDDP.simulate(
    model,
    sampling_scheme = SDDP.Historical(
        [((1, 1), Ω[1]), ((2, 2), Ω[3]), ((3, 1), Ω[2])],
    ),
)
```

Here the first number of each pair is the node index in the policy graph (this part is shown) and the second one is a NamedTuple, so both variables are receiving a value. I've tried using this idea but in our model we are using an array variable:

```julia
function variable_inflow(sp, data::Dict)
    @variables(sp, begin
        0 <= inflow[r=1:data[:n_hydro]]
    end)
end
```

And passing a NamedTuple with the variable symbol (:inflow) and an array of values (one for each entry of the array) to the Historical sampling didn't work, it says the it is not a valid index:

```julia
    Ω = [[(t, NamedTuple{(:inflow,)}( ([inflow[i,t,ω] for i in 1:data[:n_hydro]],)))
          for t in 1:data[:stages]] 
         for ω in 1:data[:n_inflow]]


    solution = SDDP.simulate(policygraph,
                         data[:n_eval_inflow],
                         interest,
                         sampling_scheme=SDDP.Historical(Ω))
```

 Do every entry of said array get its own symbol? Given that a have a scenario with inflows for each hydro plant for each stage, how can I pass it as an input to the Historical sampling?

Again, sorry if this is too obvious, but I couldn't follow from just the docs.

Thank you very much.

**Comment by odow** [comment]
Ah. The confusion is that the examples don't match the problem at the top. I guess I collated these from different places at some point.

The first element of the tuple is the node.

The second element of the tuple is a realization that will be passed to the `parameterize` function. What that is depends on your model.

A better example for the documentation would be:
```julia
SDDP.Historical([
    [
        (1, (inflow = 65.0, fuel_multiplier = 1.1)), 
        (2, (inflow = 0.0, fuel_multiplier = 0.1)),   # Can be out-of-sample
        (3, (inflow = 65.0, fuel_multiplier = 1.1)),
    ],
    [
        (1, (inflow = 65.0, fuel_multiplier = 1.1)), 
        (2, (inflow = 65.0, fuel_multiplier = 1.1)), 
        (3, (inflow = 65.0, fuel_multiplier = 1.1)),
    ],
])
```

Note that you don't have to use NamedTuples for the noise realizations. It might be more convenient just to use a regular vector.

**Comment by franciscogaluppo** [comment]
Excellent, it is working now. Thank you!

**Comment by odow** [comment]
I'll leave this open as a reminder to fix the docs.
