### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#451]
A user sent me this:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/8177701/129530426-93e8787d-f064-4bd9-8459-199dcf8ee629.png">

**Comment by odow** [comment]
Ah. They have `StatPlots` and `StatsPlots` installed.

`StatPlots` seems to be an old package before it was renamed `StatsPlots`:
https://github.com/JuliaRegistries/General/tree/master/S/StatPlots

Try `] rm StatPlots` then `] up`.

**Comment by zfornier** [comment]
It worked, SDDP is successfully updated
