### ISSUE TITLE
Historical Simulation

### ISSUE THREAD

**Issue by anavarro01** [odow/SDDP.jl#485]
Hi

I am trying to simulate a trained model with an historical simulation, but i can´t do it with the example provided [here](https://odow.github.io/SDDP.jl/stable/guides/simulate_using_a_different_sampling_scheme/#Historical-simulation). 
In context, im working on an hydro-thermal sceduling problem, and i have n > 1 nodes that have uncertenty. I use a variable called _affluent_ that have as index the ID of the node that have the affluent.
Actually im using the parameterize by this way:
```
scenarios = 5
SDDP.parameterize(sp, [sc for sc in scenarios]) do w
        for i in 1:length(nodes_names)
            JuMP.fix(affluent[nodes_names[i]], hydro_scenarios[i][w])
        end
end
```
where _nodes_names_ are just a list with the ID of the nodes and _hydro_scenarios_ is a dict() where the key is the ID of the node (that can be any number) and the value is a list of possible scenarios of inflow (i have a hydro_scenario dict for each stage).
The problem is that in the [docs](https://odow.github.io/SDDP.jl/latest/apireference/#SDDP.Historical), the historical simulation use only one variable with uncertenty:
```
Historical(
    [
        [(1, 0.5), (2, 1.0), (3, 0.5)],
        [(1, 0.5), (2, 0.0), (3, 1.0)],
        [(1, 1.0), (2, 0.0), (3, 0.0)]
    ],
    [0.2, 0.5, 0.3],
)
``` 
There is a an equivalent way to pass a symbol dict to historical scenarios to simulate the uncertenty? Like this
```
dictionary = Dict( Symbol("affluent[1]") =>21, Symbol("affluent[4]") => 23)
```
Thank you in advance!

**Comment by anavarro01** [comment]
Thanks, it worked perfectly with this solution

> `Historical` needs to be provided whatever `w` is, so you'll need to refactor your code appropriately.
> 
> Perhaps something like this:
> 
> ```julia
> scenarios = [
>     [hydro_scenarios[i][w] for i in 1:length(nodes_names)]
>     for w in 1:5
> ]
> 
> SDDP.parameterize(sp, scenarios) do ω
>     for (name, ωi) in zip(nodes_names, ω)
>         JuMP.fix(affluent[name], ωi)
>     end
> end
> ```
> 
> Then
> 
> ```julia
> Historical([
>     # (stage, realization)
>     (1, [21, 0, 0, 23]),
>     (2, [21, 0, 0, 23]),
>     (3, [21, 0, 0, 23]),
>     (4, [21, 0, 0, 23]),
> ])
> ```

**Comment by odow** [comment]
Great! The trick is to pick a good data structure for your scenarios.
