### ISSUE TITLE
How to recover the dual of a constraint array whose dimension depends on the stage of simulation

### ISSUE THREAD

**Issue by Misoto3** [odow/SDDP.jl#488]
Hi Oscar,

I'm trying to recover the dual associated with a constraint in my model, but the problem is that in certain cases b goes from 1:3 and from certain stage it goes from 1:5, so I don't know how I can recover the dual variable.

The constraint goes as follows:

`demanda_constraint[i in Data["System"]["SetBuses"], b in 1:Data["TimeBlocks"]["Size"][t]]`

And what I'm trying to do is:
```
simulation_results = SDDP.simulate(model, 1;
    custom_recorders = Dict{Symbol, Function}(
        :constraint_dual => (sp) -> [JuMP.dual(sp[:demanda_constraint][i,b] ) for i in Data["System"]["SetBuses"], b in 1:Data["TimeBlocks"]["Size"][t]]
    )
)
```
Which obviously doesn´t run, because t is not defined, and I want it to be the stage of the simulation. So I'm asking how can I do this.

Thanks in advance!

Greetings, Matias

**Comment by odow** [comment]
Use broadcasting:
```Julia
simulation_results = SDDP.simulate(model, 1;
    custom_recorders = Dict{Symbol, Function}(
        :constraint_dual => sp -> JuMP.dual.(sp[:demanda_constraint]),
    )
)
```

**Comment by odow** [comment]
JuMP docs: https://jump.dev/JuMP.jl/stable/manual/containers/#Broadcasting-2

**Comment by Misoto3** [comment]
Thanks for the quick response.

Unfortunately I don't get how to use broadcasting to recover the stage "t" of each subproblem in the simulation. It will help me a lot if you could elaborate on how to use broadcasting for this.

Thanks again!

**Comment by Misoto3** [comment]
Hi again, I discovered how to do what I wanted

```
simulation_results = SDDP.simulate(model2, 1;
    custom_recorders = Dict{Symbol, Function}(
        :constraint_dual => (sp) -> [JuMP.dual(sp[:demanda_constraint][i,b] ) for i in Data["System"]["SetBuses"], b in 1:length(axes(sp[:demanda_constraint])[2])]
    )
)
```
With this I can recover the dimension of the constraint in each subproblem (stage)

**Comment by odow** [comment]
> I don't get how to use broadcasting to recover the stage "t" of each subproblem

You shouldn't need to. It will automatically figure it out. Did you try the broadcasting? Was there an error?

>  I discovered how to do what I wanted

Great. You can also write it like this which might be more readable:
```Julia
function demand_duals(sp::Model)
    demanda_constraint = sp[:demanda_constraint]
    buses, blocks = axes(demanda_constraint)
    return [JuMP.dual(demanda_constraint[i, j]) for i in buses, b in blocks]
end

simulation_results = SDDP.simulate(model2, 1;
    custom_recorders = Dict{Symbol, Function}(
        :constraint_dual => demand_duals,
    )
)
```

**Comment by Misoto3** [comment]
The code you wrote worked perfectly, and it made the code more readable, thanks!

With the broadcasting I couldn´t really use it because I'm not familiarized with it, so I dont quite understand how I could use it to recover the dual I want.

Nevertheless, with what you sent I can do the task I wanted, thanks a lot again!

Greetings, Matias

**Comment by odow** [comment]
No problem. I'll close this issue. Please open a new one if you have other questions.

**Comment by anavarro01** [comment]
Hi, i am doing something similar, but my constraint has 3 dimensions. Let's say, continuing with the nomenclature used, that i have this constraint:
```julia
demanda_constraint[i in Data["System"]["SetBuses"], b in 1:Data["TimeBlocks"]["Size"][t], d in 1:Data["TimeBlocks"]["Days"][t]]
```
I'm trying to use this function, but it gave me an error. I think that the error it's because the constraint has 3 dimensions, but i can't figure out how to use the axis function with the constraint.
> ```julia
> function demand_duals(sp::Model)
>     demanda_constraint = sp[:demanda_constraint]
>     buses, blocks, days = axes(demanda_constraint)
>     return [JuMP.dual(demanda_constraint[i, b, d]) for i in buses, b in blocks, d in days]
> end
> ```
The error is:
```julia
JuMP.Containers.SparseAxisArray{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}},ScalarShape},3,Tuple{Int64,Int64,Int64}}
ERROR: MethodError: no method matching size(::JuMP.Containers.SparseAxisArray{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.EqualTo{Float64}},ScalarShape},3,Tuple{Int64,Int64,Int64}})
Closest candidates are:
  size(::AbstractArray{T,N}, ::Any) where {T, N} at abstractarray.jl:38
  size(::SentinelArrays.MissingVector) at /home/agnavarro/.julia/packages/SentinelArrays/VbnBp/src/missingvector.jl:6
  size(::GridLayout) at /home/agnavarro/.julia/packages/GridLayoutBase/nYdeK/src/gridlayout.jl:1276
  ...
```

**Comment by odow** [comment]
So here you probably need to use broadcasting.
```Julia
function demand_duals(sp::Model)
    return JuMP.dual.(sp[:demanda_constraint])
end
```
You'll get a  `SparseAxisArray` back, that you need to index with the same keys as the constraints. It isn't an array you can index with `1, 2, ..., n`.

**Comment by anavarro01** [comment]
Thanks, this worked perfectly.

> So here you probably need to use broadcasting.
> 
> ```julia
> function demand_duals(sp::Model)
>     return JuMP.dual.(sp[:demanda_constraint])
> end
> ```
> 
> You'll get a `SparseAxisArray` back, that you need to index with the same keys as the constraints. It isn't an array you can index with `1, 2, ..., n`.

**Comment by odow** [comment]
Great. I'm about to reply to your other question.
