### ISSUE TITLE
SDDP.simulate with known realization

### ISSUE THREAD

**Issue by juyoungwang** [odow/SDDP.jl#494]
Hi,

Previously, I have run SDDP.simulate(), and I have the list of uncertainty realizations (sample path used in simulation) stored in a database.

As I have executed the experiments without fixing seeds, I was wondering if there is any way to replicate the experiments using the list of sample paths I defined above...

Thanks for providing such an amazing package for the community!

**Comment by odow** [comment]
See https://odow.github.io/SDDP.jl/stable/guides/simulate_using_a_different_sampling_scheme/#Historical-simulation

**Comment by juyoungwang** [comment]
Thanks a lot!

**Comment by odow** [comment]
No worries. Reopen this issue if things aren't clear.

**Comment by juyoungwang** [comment]
> No worries. Reopen this issue if things aren't clear.

Hi, I was just wondering if I can get help on solving the following error:

If I execute the following code:

> simulations = SDDP.simulate(model
>                                 ,sampling_scheme = SDDP.Historical([(1, 16), (2, 2), (3, 20), (4, 4), (5, 16)])
>                                 ,[:x_t]
>                                 )

I get an error like this:

> MethodError: no method matching simulate(::SDDP.PolicyGraph{Int64}, ::Array{Symbol,1}; sampling_scheme=SDDP.Historical{Int64,Int64}(SDDP.Noise{Array{Tuple{Int64,Int64},1}}[Noise{Array{Tuple{Int64,Int64},1}}(Tuple{Int64,Int64}[(1, 16), (2, 2), (3, 20), (4, 4), (5, 16)], 1.0)]))
> Closest candidates are:
>   simulate(::SDDP.PolicyGraph) at /home/jwang/.julia/packages/SDDP/pAH7C/src/algorithm.jl:1154 got unsupported keyword argument "sampling_scheme"
>   simulate(::SDDP.PolicyGraph, !Matched::Int64) at /home/jwang/.julia/packages/SDDP/pAH7C/src/algorithm.jl:1154 got unsupported keyword argument "sampling_scheme"
>   simulate(::SDDP.PolicyGraph, !Matched::Int64, !Matched::Array{Symbol,1}; sampling_scheme, custom_recorders, require_duals, skip_undefined_variables, parallel_scheme) at /home/jwang/.julia/packages/SDDP/pAH7C/src/algorithm.jl:1154
> 
> Stacktrace:
>  [1] top-level scope at In[207]:4

While if I execute the code without variable dictionary [:x_t], I get no error.
> simulations = SDDP.simulate(model
>                                 ,sampling_scheme = SDDP.Historical([(1, 16), (2, 2), (3, 20), (4, 4), (5, 16)])
>                                 )

Do you have any idea on what's going on here?

Thanks a lot!

**Comment by odow** [comment]
You need the arguments in the correct order.
```Julia
SDDP.simulate(model, 5, [:x_t]; sampling_scheme = SDDP.Historical(...))
```
