### ISSUE TITLE
Error after updating to SDDP.jl 0.4.4

### ISSUE THREAD

**Issue by adow031** [odow/SDDP.jl#497]
After updating from SDDP.jl 0.3.17 to 0.4.4, I'm now getting the following error when simulating a model that I've previously been using.

I haven't got an MWE for this, since it's quite a big model that I'm using, but I'm hoping that you've seen this / or you understand the error `SparseAxisArray(::Dict{Any, Any})` instead of `!Matched::Dict{K, T}`...

The error seems to be thrown within JuMP, and caused by the `_simulate(...)` function in SDDP.

![image](https://user-images.githubusercontent.com/8185462/153305794-d6cd59a6-ac10-4459-9d84-35751bf9cd99.png)

Thanks in advance,
Tony.

**Comment by odow** [comment]
Are you using a custom recorder? Is JADE public? I'd have to see the example. 

To convert a dictionary to a sparse axis array, the keys need to be an `NTuple`, so something like `Dict{NTuple{3,Int},Any}`.

**Comment by odow** [comment]
Another thing that would help would be trying out `] add SDDP@0.4.0` to narrow down when we introduced the issue.

**Comment by adow031** [comment]
This is what I'm using for the custom_recorder:

    get_dual = Dict{Symbol,Function}(
        :prices => (sp) -> d.rundata.scale_objective * JuMP.dual.(sp[:defineShedding]),
        :mwv =>
            (sp) ->
                -d.rundata.scale_objective * JuMP.dual.(sp[:rbalance]) / 1E3 /
                d.rundata.scale_reservoirs,
        :mfv => (sp) -> -d.rundata.scale_objective * JuMP.dual.(sp[:useFuel]),
    )

Where do I need to set the type: `Dict{NTuple{3,Int},Any}`?

**Comment by adow031** [comment]
Also: SDDP 0.4.0 worked. (It downgraded JuMP to 0.21.10.)

**Comment by odow** [comment]
Can you try `0.4.1`, `0.4.2`, and `0.4.3`?

What happens on your `simulate.jl` line 152?

**Comment by adow031** [comment]
Thanks for your help so far; 0.4.3 works fine. The error starts when JuMP is updated to 0.22...

I've managed to track the issue down to a specific variable that I was returning for the simulation.

This has the type:
JuMP.Containers.SparseAxisArray{Any, 2, Tuple{Any, Any}} with 0 entries

The way that I declare it is standard:
```
0 <= fuelsupply[f in s.STORED_FUELS, k in 1:length(d.fuel_supply[timenow][f])] <= d.fuel_supply[timenow][f][k].q
```

I think I may have worked it out...depending on the parameters of the model ```s.STORED_FUELS``` is sometimes empty. However, even if the set has no elements, the set is still defined with a type:
`STORED_FUELS::Vector{Symbol}`

Regardless, it looks like a change in JuMP is the cause.

**Comment by adow031** [comment]
This variable doesn't cause the issue; I presume it's only for empty Tuples that this occurs.
```
@variable(
            md,
            0 <= fuel_storage[f in s.STORED_FUELS] <= d.fuel_storage[f].maximum,
            SDDP.State,
            initial_value = d.fuel_storage[f].initial
        )
```

**Comment by odow** [comment]
This is a bug in JuMP
```Julia
using JuMP
model = Model()
S = Any[]
@variable(model, x[S, S] >= 0, container = SparseAxisArray)
lower_bound.(x)
```

I'll take a look at fixing it. 

I don't have a good work-around for now, other than "don't create variables that have no elements". But that's probably painful to engineer around.

**Comment by adow031** [comment]
Thanks for finding an MWE.

When I was putting this in I originally presumed it wouldn't work. (Who would ever need a variable indexed over an empty set?)

The fact that it worked meant I didn't need if statements all over the code (both for the model, and the results), so it would be nice for it to be fixed.

Tony.
