### ISSUE TITLE
Simulating the policy section

### ISSUE THREAD

**Issue by bernardokp** [odow/SDDP.jl#499]
So, you are showing one replication for stage = 2. The first observation is that despite focusing on policy graphs, there are still lots of mentions of stages. That is a bit confusing as the reader is trying to absorb the PG mindset. 

More importantly, I am a bit lost in what you are showing for volume and thermal_generation. If it is only one replication, what do I see 3 values? Or is this the generation for each node? But then why do you have replications = 2 in the first code snippet?

I feel the displays are not well explained here.

**Comment by odow** [comment]
Closing in favor of #496
