### ISSUE TITLE
Objective states - error in the example

### ISSUE THREAD

**Issue by bernardokp** [odow/SDDP.jl#503]
Dear Oscar,

I think I spotted a basic error in your example. In the simulation you make you show that
fuel costs are 0.75, 1.1, and 0.75. Since the initial value of 50, we should have 

50*0.75 = 37.5, then 37.5*1.1 = 41.25, and finally 41.25 *0.75 = 30.9375.

This is what you have in the display, but in the text, you have something else which I cannot understand. 

Best,
Bernardo

**Comment by odow** [comment]
I obviously updated the example at some point but didn't update the text.
