### ISSUE TITLE
Is there a way to efficiently add deterministic node in policy graph?

### ISSUE THREAD

**Issue by juyoungwang** [odow/SDDP.jl#508]
Hi,

To add deterministic node which is random variable independent, I was adding a set of dummy constraint which are not affected by random variable realizations. I was wondering if there is any better way to do so.

Is there any possibility to do so?

Thanks

**Comment by odow** [comment]
I don't fully understand the question. Do you want a node with no uncertainty realizations?

There's no special support. Just don't call `parameterize` for that node:
```Julia
    if node != 5
        SDDP.parameterize(sp, realizations) do omega
            # stuff here
        end
    else
        # Node 5 is deterministic
    end
```

**Comment by juyoungwang** [comment]
That answered my question. Thanks!
