### ISSUE TITLE
The simples dynamic problem that you can solve in sddp.jl.

### ISSUE THREAD

**Issue by bernardokp** [odow/SDDP.jl#513]
Hello,

so, for people coming from other communities, or if you are a limited programmer like me, getting started with SDDP.jl can be challenging. Some people come from the MDP world, some people from (A)DP, others from Stochastic Programming...

What is the easiest example that can be solved with the package? The example must be super simple to understand, 
trivial to code, and hopefully with an intuitive solution. Well, I think I found one, and it comes with a closed-form solution: 

https://github.com/bernardokp/Multistage-DP-examples/blob/d3e239bf0d458d690b367873b93d81d53aec8f18/The%20sequential%20allocation%20model

I hope this helps you get started. 

Best,
Bernardo

**Comment by odow** [comment]
Closing in favor of https://github.com/odow/SDDP.jl/issues/496
