### ISSUE TITLE
Optimal Path and Optimal Value 

### ISSUE THREAD

**Issue by Sumeyya1** [odow/SDDP.jl#524]
Hi Oscar,

I have been using SDDP and I want to know if the problem has multiple scenarios. Is it possible to calculate the optimal path (stages, markovian states) and also the optimal value of that optimal path?

The problem I solved using SDDP has 72 scenaris. I want to find the optimal path.

Problem
  Nodes           : 13
  State variables : 4
  Scenarios       : 7.20000e+01
  Existing cuts   : false
  Subproblem structure                      : (min, max)
    Variables                               : (11, 11)
    VariableRef in MOI.LessThan{Float64}    : (6, 7)
    AffExpr in MOI.LessThan{Float64}        : (1, 1)
    VariableRef in MOI.GreaterThan{Float64} : (7, 7)
    AffExpr in MOI.EqualTo{Float64}         : (1, 1)
Options
  Solver          : serial mode
  Risk measure    : SDDP.Expectation()
  Sampling scheme : SDDP.InSampleMonteCarlo

Numerical stability report
  Non-zero Matrix range     [1e+00, 9e+03]
  Non-zero Objective range  [1e+00, 3e+04]
  Non-zero Bounds range     [1e+02, 1e+02]
  Non-zero RHS range        [2e+02, 2e+06]
No problems detected

 Iteration    Simulation       Bound         Time (s)    Proc. ID   # Solves
        1    2.882820e+07   2.187224e+07   1.900005e-02          1         17
        2    2.351164e+07   2.503558e+07   2.600002e-02          1         34
        3    2.831164e+07   2.503558e+07   2.799988e-02          1         51
        4    4.285160e+07   3.153225e+07   2.900004e-02          1         68
        5    4.285160e+07   3.153225e+07   3.099990e-02          1         85
        6    2.922397e+07   3.153225e+07   3.299999e-02          1        102
        7    2.393904e+07   3.153225e+07   3.499985e-02          1        119
        8    2.351164e+07   3.153225e+07   3.699994e-02          1        136
        9    4.285160e+07   3.153225e+07   4.999995e-02          1        153
       10    2.351164e+07   3.153225e+07   5.200005e-02          1        170

Terminating training
  Status         : iteration_limit
  Total time (s) : 5.200005e-02
  Total solves   : 170
  Best bound     :  3.153225e+07
  Simulation CI  :  3.093926e+07 ± 5.285649e+06

**Comment by odow** [comment]
> optimal path.

I don't know what this means. You want to find the scenario with the minimum cost? There's no way to obtain this, and it doesn't make much sense. The paths are random, so there isn't a single "optimal" path.

The optimal solution is a policy: 

 * https://odow.github.io/SDDP.jl/stable/tutorial/basic/01_first_steps/
 * https://odow.github.io/SDDP.jl/stable/tutorial/theory/21_theory_intro/

**Comment by odow** [comment]
Bump. Is there anything actionable here? If no, I will close.

**Comment by odow** [comment]
Closing because it's not possible to compute an optimal path.
