### ISSUE TITLE
Incorporate the information N stages before in subproblems

### ISSUE THREAD

**Issue by Moon1193** [odow/SDDP.jl#530]
Hi Oscar,
We are modelling the optimization for a hydroelectric cascade system, one of the constraints is a dynamic equation which includes decision variable of current node, its parent node (1 stage before) and so on (N stages before) 

We want to incorporate them in each subproblem. I know that we can add the decision variable as state variable to access the current node and parent node information but is there any way we can also incorporate the variables at N(N>1) stages before.

We would be grateful if you could give us some suggestions on how to solve this problem.

**Comment by odow** [comment]
If you need to access a variable from a previous stage, then it **must** become a state variable. 

See https://odow.github.io/SDDP.jl/stable/guides/acess_previous_variables/

**Comment by Moon1193** [comment]
Thank you for the information.

**Comment by odow** [comment]
Closing because this seems resolved. Please re-open if you have other questions.
