### ISSUE TITLE
How SDDP works in an example?

### ISSUE THREAD

**Issue by lfelipebueno** [odow/SDDP.jl#553]
Hi! Your tutorial is very good. However I think that the method behind it could be better understood is you ilustrate it on the example constructed in the Introduction section. Congratulate! Thanks a lot!

**Comment by odow** [comment]
> However I think that the method behind it could be better understood is you illustrate it on the example constructed in the Introduction section.

I'm not sure I understand the suggestion.

Do you mean that this example:
https://odow.github.io/SDDP.jl/latest/tutorial/theory/21_theory_intro/#Functions

should be the same as:
https://odow.github.io/SDDP.jl/latest/tutorial/basic/01_first_steps/#Example:-hydro-thermal-scheduling

**Comment by odow** [comment]
Closing because the examples are the same. There's a little bit of Julia syntax difference, but that's because we're not building a fully fledged implementation.

If I mis-understood, please reopen and provide more details :smile: Other suggestions are always appreciated.
