### ISSUE TITLE
Can your framework solve large scale problems

### ISSUE THREAD

**Issue by hghayoom** [odow/SDDP.jl#569]
Hi. 
Thanks for your great package. It is honestly advanced. 
I want to use it to solve my PhD problem. But It may be a large-scale problem with a lot of decision variables and a lot of uncertainties. 
Before jumping to the formulation and getting stuck in solving that problem, I am wondering if you have any idea about the capability of your framework for solving large-scale problems? your examples are simple. Have you tested that for larger problems?

Thanks

**Comment by odow** [comment]
From the README

> SDDP.jl is a package for solving large multistage convex stochastic programming problems

So the short answer is "Yes."

But define "large-scale."

If you have a multistage stochastic program for which SDDP is applicable, then we can probably solve it. If we can't then you probably don't have an alternative method that can.

But we have run problems with hundreds of state-variables and nodes.

**Comment by hghayoom** [comment]
WWooooooooW. 
That is really Great. 
I have searched a lot and there is not anything like yours. I just wanted to double-check. 
I would appreciate it if you also can direct me to any large-scale problems examples or papers using your framework to better grasp it.

**Comment by odow** [comment]
> to any large-scale problems

Again, define "large-scale." Some large problems are easy to solve. Some small problems can never be solved. The answer is likely problem-dependent. 

However...

List of papers and links to code:

 * https://odow.github.io/SDDP.jl/latest/#Citing-SDDP.jl
 * https://github.com/odow/SDDP.jl/tree/master/papers

Google Scholar link

 * https://scholar.google.com/scholar?hl=en&as_sdt=2005&sciodt=0,5&cites=500964028472401726&scipsc=&q=&scisbd=1

A few random examples:
 
 * https://ieeexplore.ieee.org/abstract/document/9546644
 * https://eventos.fgv.br/sites/eventos.fgv.br/files/arquivos/u1252/poster_williams_yanes.pdf
 * https://jfin-swufe.springeropen.com/articles/10.1186/s40854-022-00433-7

**Comment by odow** [comment]
> I have searched a lot and there is not anything like yours

The closest is https://github.com/lingquant/msppy but it isn't maintained anymore.

**Comment by hghayoom** [comment]
Excellent. 
Thanks

**Comment by odow** [comment]
Closing because this isn't a bug in SDDP.jl. Please open a new issue if you have questions once you start using the library.
