### ISSUE TITLE
Simulate over the same Monte Carlo scenarios

### ISSUE THREAD

**Issue by AngeBlanchard** [odow/SDDP.jl#570]
Hi,
I would like to train some policies over the same set of scenarios, in order to compare them.
For now, I use SDDP.Historical, but it's not convenient to simulate hundreds of paths.

Do you know if we can save the Monte Carlo scenarios somewhere to be used later ? Or am I doomed to write manually all the scenarios I want to implement and fit them into the SDDP.Historical function ?

Thanks for your help,
Ange

**Comment by odow** [comment]
You could do something like:
```julia
scenarios = [sample_scenario(model, SDDP.InSampleMonteCarlo()) for _ in 1:100]
sampling_scheme = SDDP.Historical(scenarios)
SDDP.train(
    model;
    sampling_scheme = sampling_scheme
)
SDDP.simulate(model, 100; sampling_scheme = sampling_scheme)
```

or perhaps

```julia
sampling_scheme = SDDP.PSRSamplingScheme(100)
SDDP.train(
    model;
    sampling_scheme = sampling_scheme,
    iteration_limit = 100,
)
SDDP.simulate(model, 100; sampling_scheme = sampling_scheme)
```

**Comment by AngeBlanchard** [comment]
Hi, thanks a lot for your response.
I needed to modify the code a little bit to make it operational on my model, maybe it's specific to my personal case but I drop my code below anyway:

```
scenarios = [SDDP.sample_scenario(model, SDDP.InSampleMonteCarlo())[1] for _ in 1:100]
sampling_scheme = SDDP.Historical(scenarios)
SDDP.simulate(model, 100; sampling_scheme = sampling_scheme)
```

Hence, I had to drop the boolean value by specifying I wanted the first (```[1]```) element of `SDDP.sample_scenario`. Otherwise, I had some issues when simulating.

Hope this can help, and thanks again,
Regards,
Ange

**Comment by AngeBlanchard** [comment]
Before closing, I just realised that all the scenarios I got with this implementation don't consider the possible change in Markov state (each node is of the form (t,1) with t the time index).

My model uses a markov policy graph, and ideally I would like to test my policies over scenarios with markov states changing from 1 to 2, according to the respective probabilities
Do you know how to handle it ?

Many Thanks,
Ange

**Comment by odow** [comment]
Sampling with the in-sample Monte Carlo should also sample over the Markov states. If it is just returning `(t,1)`, then there is a problem with the definition of your graph.

It's hard to say more without a reproducible example.

**Comment by AngeBlanchard** [comment]
Oh yeah you're right, that's on me.
Thanks again, I close then, I do not have any issue left.
Have a good day !

**Comment by odow** [comment]
> I do not have any issue left.

Great! Let me know if you have other questions.
