### ISSUE TITLE
Typo in API Reference

### ISSUE THREAD

**Issue by jarandh** [odow/SDDP.jl#576]
Hi, just letting you know that there is a typo in the API Reference on SDDP.simulate. It says incoming_state::Dict{String,Float64} = _intial_state(model) and not _initial_state(model).

**Comment by odow** [comment]
Just waiting to the documentation to finish rebuilding, https://github.com/odow/SDDP.jl/actions/runs/4537537276/jobs/7995489922, and then it'll be updated here: https://odow.github.io/SDDP.jl/latest/apireference/#SDDP.simulate.

If you spot other mistakes, you can edit the file by navigating to https://github.com/odow/SDDP.jl/blob/master/src/algorithm.jl, and then clicking the "edit this file" icon:

![image](https://user-images.githubusercontent.com/8177701/228089828-f47f43b1-1d1b-4bd0-b804-9c7327701981.png)

Make any changes, then scroll to the bottom and follow the instructions (essentially, just click the green buttons) to create a new pull request.

**Comment by odow** [comment]
Fixed by #577
