### ISSUE TITLE
Implement MIDAS on SDDP.jl

### ISSUE THREAD

**Issue by caioluke** [odow/SDDP.jl#609]
Hi Oscar,

I have recently fallen in love with your package (it took me a while but it finally hit on me!) and I would like to contribute to it.

One ideia that came to my mind was to implement the MIDAS algorithm (step-cuts) to handle integrality in SDDP.

Here's the paper: https://www.epoc.org.nz/papers/PhilpottWahidBonnansR1.pdf

Do you think that it would be worth the time to do it?

If you have any other more useful features to be implemented in the pipeline I suppose we could talk about them.

Here's my email: caioluke97atgmaildotcom

Thank you for the amazing work!

**Comment by caioluke** [comment]
Ha! Funny coincidence.

Thanks for the input. I suppose I fell into the trap of wanting to get the best I can get from a model (its optimum) while forgetting that my model has a reality gap, therefore the best it can provide is not necessarily the best solution for my real life application!

"Ceci n'est pas une pipe" as Magritte once said.

Ok, I'll have a look at #419 at try to implement it soon enough. :)

**Comment by odow** [comment]
Thanks for the suggestion. But I think I'm going to close this as "won't-fix." 

Feel free to open any other issues with suggestions :smile:

**Comment by odow** [comment]
@caioluke if you're interested, take a look at https://github.com/odow/SDDP.jl/pull/611
