### ISSUE TITLE
documentation fix

### ISSUE THREAD

**Issue by slwu89** [odow/SDDP.jl#616]
I noticed the code block in "Access a first-stage decision in a future stage" of this help page (https://odow.github.io/SDDP.jl/stable/guides/access_previous_variables/) needs the following changes to run when using `SDDP.train` on the resulting model:

  1. `capcity` variable name misspelled when defined in `@variable` macro
  2. `capacity` variable needs to be constrained to be non-negative
  3. current version of SDDP needs a `upper_bound` defined when the sense is `:Max`

**Comment by odow** [comment]
I should update these so that the code actually gets tested when the documentation builds 😆 

See https://github.com/odow/SDDP.jl/pull/617
