### ISSUE TITLE
Running into some error (MSPFormat reader)

### ISSUE THREAD

**Issue by bonnkleiford** [odow/SDDP.jl#637]
Hi Oscar,

I was trying the MSPFormat reader function to try energy problem. Unfortunately, I ran into some error where one of the coefficients (price_6) of the objective function is not found. Here is the full error:

<img width="723" alt="Screenshot 2023-07-06 at 21 25 55" src="https://github.com/odow/SDDP.jl/assets/37835698/132853fe-9223-458f-a9f8-a499085f053f">

Here are the two JSON files (problem and lattice) for reproduction purposes:
[Energy.zip](https://github.com/odow/SDDP.jl/files/11971561/Energy.zip)

Best,
BIKEY

**Comment by odow** [comment]
That's this line:
https://github.com/odow/SDDP.jl/blob/e2e1ecb909f59fe51095250ca91a326d8565c543/src/MSPFormat.jl#L38

I think we discussed this, but I don't remember the conclusion. If a node i the lattice was missing a random variable, should we infer the value to be `0.0`? 

I'll re-iterate that I think this is a bad idea and a recipe for bugs. There's no need for file formats to be clever or save space. The zip file with and without the default values should be pretty similar.
