### ISSUE TITLE
Intro issue: ability to pass a function into SDDPModel instead of jagged arrays

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#64]
As suggested by @adow031, it might be easier to specify objective bounds and transition matrices via a function that takes as input the stage and markov state instead of forming jagged arrays. For example
```julia
function foo(t::Int,i::Int)
    100 * t + i
end

SDDPModel(
    objective_bound = foo
) do sp, t, i

end
```
Instead of
```julia
SDDPModel(
    objective_bound = [ [101, 102, 103], [201, 202, 203], ... ]
) do sp, t, i

end
```

This would require adding a the following method to https://github.com/odow/SDDP.jl/blob/master/src/utilities.jl#L70
```julia
getel(T, f;:Function, t::Int, i::Int) = f(t,i)
```
along with some tests.

**Comment by adow031** [comment]
The function should also take the number of stages.

If maximising, I think a standard implementation (without Markov states) would look something like:

objective_bound = max(max_total_objective,(states - t)*max_profit_per_state + max_end_of horizon_profit)

**Comment by odow** [comment]
It's up to the user to capture that as a closure.
```julia
objective_bound = (t,i)->max(max_total_objective,(states - t)*max_profit_per_state + max_end_of horizon_profit)
```
