### ISSUE TITLE
Unclear tutorial: introductory theory

### ISSUE THREAD

**Issue by sigmundholm** [odow/SDDP.jl#648]
In struggling with understanding the [tutorial](https://github.com/odow/SDDP.jl/blob/master/docs/src/explanation/theory_intro.jl), specifically under the section `Preliminaries: approximating the cost-to-go term`. In the forth paragraph, could you specify in equations, the *"reduced cost of the decision variable $\bar{x}$"*, which is referred to the *"subgradient of the function $V_i$ with respect to $x$*".

**Comment by odow** [comment]
Hi there. I don't know if I understand. What part is unclear?

**Comment by odow** [comment]
Would it help if I added the link `[reduced cost](https://en.wikipedia.org/wiki/Reduced_cost)`?

https://en.wikipedia.org/wiki/Reduced_cost

**Comment by odow** [comment]
Any suggestions? I'm very interested in improving the documentation for people learning SDDP, but it's hard for me to know what parts need work.

If not, I will give this a few days and then close.

**Comment by sigmundholm** [comment]
Yes, adding the link would help. It would also help stating in equations what the *reduced cost* is in this case.

**Comment by sigmundholm** [comment]
For me it would help if the text maybe was something like this:
[...] then the [reduced cost](https://en.wikipedia.org/wiki/Reduced_cost) of the decision variable $\bar{x}$ is a subgradient of the function $V_i$ with respect to x (i.e. $\frac{d}{dx}V_i(x, .)$)!. Just to emphasize what a subgradient is.
