### ISSUE TITLE
FEASIBILITY_SENSE returned by SDDP.deterministic_equivalent()

### ISSUE THREAD

**Issue by WalterMadelim** [odow/SDDP.jl#672]
Hi, odow. I'm learning your package through
Documentation / Examples / (the 1st) Fast: the hydro thermal problem
```julia
function fast_hydro_thermal()
    model = SDDP.PolicyGraph(...
    ) do sp, t
        ...
    end
    det = SDDP.deterministic_equivalent(model, Gurobi.Optimizer)
    set_silent(det)
    # Notice the output here:
    println(objective_sense(det)) # FEASIBILITY_SENSE
    println(objective_function(det)) # 5 p#1 + 2.5 p#2 + 2.5 p#2
    JuMP.optimize!(det)
    println(objective_value(det)) # 10.0
    ...
    return
end

fast_hydro_thermal()
```
It seems the JuMP model `det` returned from your `SDDP.deterministic_equivalent()` function is having an objective with FEASIBILITY_SENSE.
I'm not quite clear about the meaning.

**Comment by odow** [comment]
It looks like we set the objective function but not the objective sense:
https://github.com/odow/SDDP.jl/blob/1f8d36b37a96995b4d62b7eaa08656630c04b899/src/deterministic_equivalent.jl#L152-L159

**Comment by WalterMadelim** [comment]
Thanks🙂

**Comment by odow** [comment]
No problem. A release will be out sometime today: https://github.com/odow/SDDP.jl/pull/674
