### ISSUE TITLE
First Stage Stopping Rule Issue

### ISSUE THREAD

**Issue by SolidAhmad** [odow/SDDP.jl#688]
I tried to use the SDDP.FirstStageStoppingRule() function on my Markovian model: 

`SDDP.train(model;  stopping_rules = stopping_rules = [FirstStageStoppingRule()], dashboard = true)`

And I get that the function is not defined, what could be the reason? 

`'UndefVarError: FirstStageStoppingRule not defined' `

I tried calling BoundStalling stopping rule and it is working, and I checked my local package files and found that the changes made [here](https://github.com/odow/SDDP.jl/pull/634/files#diff-a4f12fc2dff8347b352c39ed21846031ccb5cb5c25b7fb98d79dd1899d54b3f1) are present.

**Comment by odow** [comment]
You need `SDDP.FirstStageStoppingRule`

**Comment by odow** [comment]
As a word of caution: I only added `FirstStageStoppingRule` for a model that `@jarandh` was working on. I've never actually used it in anger, so I don't know how well it performs.

**Comment by SolidAhmad** [comment]
Thank you! I will see how it turns out in my case; I am experimenting with the different stopping rules.

**Comment by odow** [comment]
See also https://github.com/odow/SDDP.jl/issues/178

**Comment by SolidAhmad** [comment]
Thats very helpful, thank you!

**Comment by odow** [comment]
No problem. Closing because this seems resolved.
