### ISSUE TITLE
Undefined variable in out-of-sample-sampling documentation 

### ISSUE THREAD

**Issue by HenriDeh** [odow/SDDP.jl#691]
The documentation at https://sddp.dev/stable/guides/simulate_using_a_different_sampling_scheme/#Out-of-sample-Monte-Carlo-simulation uses an Omega that does not appear to be defined. Specifically:

```
sampling_scheme = SDDP.OutOfSampleMonteCarlo(model) do node
    stage, markov_state = node
    if stage == 0
        return [SDDP.Noise((1, 1), 1.0)]
    elseif stage == 3
        children = SDDP.Noise[]
        noise_terms = [SDDP.Noise((inflow = 75.0, fuel_multiplier = 1.2), 1.0)]
        return children, noise_terms
    else
        probability = markov_state == 1 ? [1/6, 1/3, 1/2] : [1/2, 1/3, 1/6]
        noise_terms = [SDDP.Noise(ω, p) for (ω, p) in zip(Ω, probability)] # the Omega in the zip
        children = [
            SDDP.Noise((stage + 1, 1), 0.5), SDDP.Noise((stage + 1, 2), 0.5)
        ]
        return children, noise_terms
    end
end
```
The same is true for other examples on the same page.

PS: big fan of the package, it's so simple.

**Comment by odow** [comment]
Omega is defined at the top of the page
![image](https://github.com/odow/SDDP.jl/assets/8177701/d6ef9bc2-db45-4d98-bcb2-acb6b3c2a843)

but you're right that it is confusing if you look lower down the page.

I'll change the docs to make it more explicit.

> big fan of the package, it's so simple.

Thanks!
