### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by pauleseifert** [odow/SDDP.jl#701]
Hi Oscar,

I found a small inconsistency in the documentation of the stopping rule. According to the documentation, passing a vector of stopping criteria results in an AND logic for all passed conditions. Reading from the documentation: 

> StoppingChain(rules::AbstractStoppingRule...)
Terminate once all of the rules are statified.
This stopping rule short-circuits, so subsequent rules are only tested if the previous pass.

However, passing SDDP.IterationLimit() in the vector overwrites the iteration limit in the SDDP.train() function, if empty, and thus results in an OR logic and stops once the iteration limit is reached. 
```Julia

```     if time_limit !== nothing
        push!(stopping_rules, TimeLimit(time_limit))
    end

**Comment by odow** [comment]
So the `stopping_rules` argument to train
https://github.com/odow/SDDP.jl/blob/cb89e07e93f314b0ea2ce1aaa770123e1b102a2f/src/algorithm.jl#L873-L874
accepts a vector of rules. Time and iterations limits are added if specified:
https://github.com/odow/SDDP.jl/blob/cb89e07e93f314b0ea2ce1aaa770123e1b102a2f/src/algorithm.jl#L1057-L1072

The elements in `stopping_rules` act as an OR: we will stop if any of the rules are true.

`StoppingChain` is a particular stopping rule that uses an AND criteria:
https://github.com/odow/SDDP.jl/blob/cb89e07e93f314b0ea2ce1aaa770123e1b102a2f/src/plugins/stopping_rules.jl#L232-L246
You can pass a `StoppingChain` as one of the rules to `stopping_rules`.
```julia
SDDP.train(model; stopping_rules = [SDDP.StoppingChain(SDDP.IterationLimit(100), SDDP.TimeLimit(100.0))])
```

Can you like to part of the docs where this could be clarified?

**Comment by pauleseifert** [comment]
Right. This applies only if using the stopping chain. I was expecting the same behaviour by only using a vector of stopping rules to automatically convert to a stopping chain. Then a small addition to the documentation in https://github.com/odow/SDDP.jl/blob/cb89e07e93f314b0ea2ce1aaa770123e1b102a2f/docs/src/guides/choose_a_stopping_rule.md?plain=1#L25 would do the trick for me. 

## Stopping rules

In addition to the limits provided as keyword arguments, a variety of other
stopping rules are available. These can be passed to [`SDDP.train`](@ref)
as a vector to the `stopping_rules` keyword. _Training stops if any of these rules becomes active. For a union of stopping rules use  [`StoppingChain()`](@ref)._

For_ example:

```julia
SDDP.train(model, stopping_rules = [SDDP.BoundStalling(10, 1e-4), SDDP.TimeLimit(100.0)])

SDDP.train(model; stopping_rules = [SDDP.StoppingChain(SDDP.IterationLimit(100), SDDP.TimeLimit(100.0))])
```

See [Stopping rules](@ref api_stopping_rules) for a list of stopping rules
supported by SDDP.jl.

**Comment by odow** [comment]
Here you go: https://github.com/odow/SDDP.jl/pull/706
