### ISSUE TITLE
Is it applicable when the local problems of some stages are mixed interger linear programming?

### ISSUE THREAD

**Issue by sunnyccshine** [odow/SDDP.jl#724]
I have a multi stage stochastic programming problem. The state variables are continuous variables and the objective functions are linear, but the local problems of some stages are mixed interger linear programming. Could you please clarify if the software is suitable for this problem. 
Is this question related to the SDDiP problem? I noticed that SDDiP problems involve integer variables in both the state variable and the objective function. However, I am uncertain whether the presence of 0-1 variables in the local problem qualifies it as an SDDiP. If you could provide clarification to resolve my confusion, I would greatly appreciate it.

**Comment by odow** [comment]
Could you please clarify if the software is suitable for this problem.

Yes, although it might not find an optimal policy.

See https://sddp.dev/stable/guides/add_integrality/

**Comment by odow** [comment]
Closing, but please comment if you have other questions and I can re-open.
