### ISSUE TITLE
Out of Sample Simulation for the infinite horizon problem. 

### ISSUE THREAD

**Issue by mcwaga** [odow/SDDP.jl#728]
Hello SDDP.jl Team,

I'm working with an infinite horizon problem in SDDP.jl and facing a challenge regarding the length of the simulations. In my current setup, each simulation yields scenarios of varying lengths since the transition probabilities do not sum up to 1. 

Objective: I aim to ensure that all simulations generated are of a fixed, predefined length.

I would really appreciate any advice or suggestions on strategies or modifications within SDDP.jl that could help achieve uniform-length simulations in this context. Is there a way to adjust the graph and probabilities or use a specific feature of SDDP.jl to maintain a consistent scenario length across simulations?

Thank you for your assistance

Best Regards,

**Comment by odow** [comment]
Hi @mcwaga, see https://sddp.dev/stable/guides/create_a_general_policy_graph/#Simulating-non-standard-policy-graphs

**Comment by mcwaga** [comment]
Thanks!

**Comment by mcwaga** [comment]
Thanks!
