### ISSUE TITLE
PublicationPlots do not check for non-finite data

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#737]
From an un-named person on WhatsApp:

<img width="913" alt="image" src="https://github.com/odow/SDDP.jl/assets/8177701/6536358c-5873-4722-bba6-67c690baa944">

**Comment by bernardokp** [comment]
Thanks for the suggestion.

Signed: Unknown person

**Comment by odow** [comment]
We'd need to check the finiteness in 
https://github.com/odow/SDDP.jl/blob/66096558ae9ba652086d954b156b809361c519ee/src/visualization/publication_plot.jl#L16-L17

But I think we should still accept `NaN`. So just `+-Inf`.
