### ISSUE TITLE
Best Practices for custom cut selection heuristic

### ISSUE THREAD

**Issue by jk27182** [odow/SDDP.jl#741]
Dear Oscar,

first of all, thank you very much for this nice package.
I am very new to Julia, so I hope this not a duplicate. I wanted to play around with cut selection for my thesis, using the `LevelOneCutOracle` you mentioned in your SDDP.jl [paper](https://optimization-online.org/wp-content/uploads/2017/12/6388.pdf).

However, the explicit function seems to be removed in versions>0.0.2 so I was wondering if there are best practices to implement my own cut selection routine without messing too much with the SDDP.jl internals.

I found the `_add_cut` and `_add_cut_selection_update` functions in src/plugins/bellman_functions.jl, should that be the functions which I extend with my own cut selection heuristic?

Best regards

**Comment by odow** [comment]
That version of the paper was never published, and you're right, LevelOneCutOracle has since been deleted.

There is no way to implement your own cut selection heuristic, other than by directly modifying the internal code of SDDP.jl.

**Comment by jk27182** [comment]
Thank you 👍

**Comment by odow** [comment]
No problem. Closing as won't-fix, since I don't intend to reconsider this decision.
