### ISSUE TITLE
Multiply two variables

### ISSUE THREAD

**Issue by wrx1990** [odow/SDDP.jl#744]
Define two variables, meeting the condition constraints with a product less than or equal to 0, how should it be written.
```
@variable(subproblem, a)
@variable(subproblem, b)
@constraint(subproblem,a*b<=0)
```

**Comment by odow** [comment]
The high-level answer: you cannot multiply two variables in SDDP.jl. That is a non-convex constraint.

A slightly more nuanced answer: you can multiply two variables in SDDP.jl if you use a solver like Gurobi.jl, but the resulting policy may be suboptimal.

**Comment by wrx1990** [comment]
Thank you for your humorous response！
