### ISSUE TITLE
Does `SDDP.jl` support modeling with endogenous uncertainty and custom decision rules?

### ISSUE THREAD

**Issue by WuSiren** [odow/SDDP.jl#745]
First of all, I would like to extend my sincere admiration to the developers of this great package! 

May I ask here some questions about the potential functionality of `SDDP.jl`?

Q1: Does the package support endogenous or decision-dependent uncertainty? If not currently supported, are there plans for future implementation?

Q2: Does the package allow for user-defined parameterized decision rules, such as an affine decision rule? If not, are there plans for future support? (What would be the complexity of adding such features? How long might it take to implement?)

Looking forward to your reply at your convenience! Thank you in advance!

**Comment by odow** [comment]
Q1: this directory mentions a not-yet public paper: https://github.com/odow/SDDP.jl/tree/master/papers/mdp. I'm not going to explain or answer questions on the code yet, but you're welcome to read it.

Q2: no support and no future plans. I don't have any idea about the complexity of adding such features, and I don't know how long it would take. The code is open-source though so you're welcome to make a fork and try something :smile:

**Comment by odow** [comment]
The issue at https://github.com/odow/SDDP.jl/issues/696 was more about simulating other decision-rules. We wouldn't provide a way to train LDRs, for example.
