### ISSUE TITLE
Can I define a constraint that correlates state variables from multiple nodes?

### ISSUE THREAD

**Issue by WuSiren** [odow/SDDP.jl#749]
For example, there is a state variable $x_t$ for stage $t$ in a multistage problem and this variable is required to satisfy, say $x_t + x_{t+1} + x_{t+2} \leq 10$. Does `SDDP.jl` support this kind of state transition constraints? How can I define it in the subproblem?

Thanks!

**Comment by odow** [comment]
See https://sddp.dev/stable/guides/access_previous_variables/
