### ISSUE TITLE
ERROR: TypeError: in keyword argument incoming_state, expected Dict{Symbol, Float64}, got a value of type Dict{Symbol, Any}

### ISSUE THREAD

**Issue by WuSiren** [odow/SDDP.jl#754]
``` julia
ERROR: TypeError: in keyword argument incoming_state, expected Dict{Symbol, Float64}, got a value of type Dict{Symbol, Any}
```
It comes after I run 
``` julia
solution = SDDP.evaluate(
    rule;
    incoming_state = state,
    noise = ω,
)
```
where `state` is a dictionary of all the state variables among which there are matrix state variables.

**Comment by odow** [comment]
Per the error: `state` must be a `Dict{Symbol, Float64}`.

See `model. initial_root_state` for an example of what it needs to be.
