### ISSUE TITLE
How to save a trained model?

### ISSUE THREAD

**Issue by WuSiren** [odow/SDDP.jl#757]
How to save a trained model? I've tried to save it with `JLD2`, but when I loaded the model, it told:
``` julia
Error showing value of type JLD2.ReconstructedMutable{Symbol("PolicyGraph{Int64}"), (:objective_sense, :root_node, :root_children, :initial_root_state, :nodes, :belief_partition, :most_recent_training_results, :ext, :timer_output), Tuple{JLD2.ReconstructedPrimitive{:OptimizationSense, UInt32}, Int64, Vararg{Any, 7}}}:
ERROR: UndefRefError: access to undefined reference
```
So is there any proper method to saving a SDDP model?

**Comment by Thuener** [comment]
You can try https://sddp.dev/stable/apireference/#SDDP.write_to_file, but it is still experimental.

What I have done was to use https://sddp.dev/stable/apireference/#SDDP.write_cuts_to_file https://sddp.dev/stable/apireference/#SDDP.read_cuts_from_file. 

I create a function to save all the parameters (save_parameters) that I use to create the subproblems into a .json file and then another load function to create the subproblems (load_parameters) using that .json file. Then, I create two functions: save_model, which calls save_parameters and write_cuts_to_file, and load_model, which calls load_parameters and read_cuts_from_file.

**Comment by odow** [comment]
You can not save a model to JLD2 because it will contain references to the underlying solver like Gurobi.

As @Thuener suggests, you should write cuts to a file.

Note that StochOptFormat is currently experimental. 

My suggestion would be to share the script that rebuilds the model as Julia code, and also share the cuts `.json` file that you can read with `read_cuts_from_file`.

**Comment by odow** [comment]
> or a new small optimization problem whose solution is the decision

It's this

**Comment by odow** [comment]
> without providing the explicit model script to the user

No, you should still provide the script.

See, e.g., https://github.com/odow/SDDP.jl/blob/master/papers/policy_graph/paper.jl and https://github.com/odow/SDDP.jl/blob/master/papers/policy_graph/powder_data.json
