### ISSUE TITLE
Performance enhance (Direct Model)

### ISSUE THREAD

**Issue by Thuener** [odow/SDDP.jl#768]
I'm dealing with a very big model and trying to increase its performance. I saw some mentions of direct_model in the code. Can we use the JuMP direct model with SDDP? Even with binary and Interger variables? What are the implications of using it?

**Comment by odow** [comment]
Note that
https://github.com/odow/SDDP.jl/blob/73dd799e9ff525d3b171719779bcda109799f05b/src/user_interface.jl#L939-L941

I realized the reason:

https://github.com/odow/SDDP.jl/blob/73dd799e9ff525d3b171719779bcda109799f05b/src/algorithm.jl#L295-L306

We can't attempt numerical recovery, and it is common enough that the problems I used direct-mode on just led to problems.

So I think I'm going to close this as won't-fix. You can use it if you want, but I don't want to document it for less-experienced users :smile:
