### ISSUE TITLE
Rename SDDP.show

### ISSUE THREAD

**Issue by roporte** [odow/SDDP.jl#78]
Hi,

I have an issue with the show function applied in a SimulationPlot variable like is described in draft_paper.pdf. When i use show(simPl) the plot never occurs and i see in console all data structure of the variable. 
Has anyone experienced this issue? How did you solve it?

Thanks!
Rodrigo Porteiro

**Comment by odow** [comment]
Make sure you are using `SDDP.show(simPI)`. If that still doesn't work, what platform are you using? I've only really tested on windows. 

I should probably overload the base show function properly so we don't have this issue.

**Comment by roporte** [comment]
Thanks! I was using show assuming that was correct!. Now it works!

**Comment by odow** [comment]
`SDDP.show` should be fixed so this doesn't happen again.
