### ISSUE TITLE
Counting the number of cuts

### ISSUE THREAD

**Issue by AngeBlanchard** [odow/SDDP.jl#787]
Hi,
I was wondering if it was possible to know the number of cuts added to a specific policy.
I  guess the number of cuts is approximately equal to the number of iterations in the training phase, but I think it's not exactly equal since some cuts can be deleted (as far as I understood)
So, how can one know the exact number of cuts in a given policy?
Thanks a lot
Ange

**Comment by odow** [comment]
> I guess the number of cuts is approximately equal to the number of iterations in the training phase

This depends on the graph structure. If you have a linear policy graph, then yes. Otherwise, no.

> So, how can one know the exact number of cuts in a given policy?

Why do you want to know this?

Note that we have a number of different "types" of cuts: single-cut, multi-cut, risk-set cuts, etc.

**Comment by AngeBlanchard** [comment]
Thanks for your answer. I’m asking because a reviewer wants details about my model, and they ask for the number of cuts. I thought there was a built in function to find that information but I guess there is not ?

my model is a linear tree graph, with only single cuts I think.

**Comment by odow** [comment]
Just tell them the number of iterations.

**Comment by AngeBlanchard** [comment]
Ok great, thanks for your help.
