### ISSUE TITLE
Best way to use historical inflow data in dams model

### ISSUE THREAD

**Issue by roporte** [odow/SDDP.jl#79]
Hi, 

Im developing an example of hydro dams model. I want to use some historical data to generate trajectories extracting series directly from weekly data in a deterministic way. The first trajectory to use gets the first week of history and advances in that serie, the second trajectory gets the second week and so on. If historical data is shorter than trajectory i get modulus and get the initial data again. When trying to develop in this way i cant find a way in the framework to get the trajectory identifier to index the first week that i must take (if first trajectory the initial week must be week 1, if nth trajectory the initial week must be nth % size). Anyone had this issue? Any suggestions to avoid changing framework code? 

Thanks,
Rodrigo

**Comment by odow** [comment]
Do you want to use this sampling strategy in the cutting phase of the algorithm or the simulation phase?

If it is the simulation phase, there is a way to do [historical simulations](https://odow.github.io/SDDP.jl/build/apireference.html#SDDP.simulate) although this isn't the easiest to use (see https://github.com/odow/SDDP.jl/issues/10).

If it is the iteration phase, then unfortunately there is _not_ a way to do it. At various points, we have discussed some sort of sampling oracle that enabled different sampling strategies to be used (for example, it would be nice to sample with the risk-adjusted probabilities https://github.com/odow/SDDP.jl/issues/29). This should be implemented at some point.
