### ISSUE TITLE
Recording primal/dual iterates

### ISSUE THREAD

**Issue by FSchmidtDIW** [odow/SDDP.jl#791]
Hi Oscar, 

in this [working paper](https://arxiv.org/html/2312.08556v1) you show a very nice plot that shows how first-stage states converge with the number of iterations. Is there a quick way to record the current (first-stage) choices for a given iteration?

I was going to do it like this but it seems a little impractical (I have not run this yet):
```julia

out = Dict{Int64,Dict}()

SDDP.train( model,
            time_limit = 18*3600,
            iteration_limit = 100,
            stopping_rules = [SDDP.FirstStageStoppingRule()],
            cut_type = SDDP.SINGLE_CUT,
            forward_pass = SDDP.RegularizedForwardPass(),
            log_file = string(today())*"sddp_serial.log"
            );
k = 100
while k<=1000
   out[k] = SDDP.simulate(model,1,...,[capacities],...)

   SDDP.train( model,
            time_limit = 18*3600,
            add_to_exisiting_cuts = true
            iteration_limit = 10,
            stopping_rules = [SDDP.FirstStageStoppingRule()],
            cut_type = SDDP.SINGLE_CUT,
            forward_pass = SDDP.RegularizedForwardPass(),
            log_file = string(today())*"sddp_serial.log"

            );
          k+= 10
end
```

Thank you,

Felix

![image](https://github.com/user-attachments/assets/b310b2f6-c4d7-486e-9da1-a75c0dcc8325)

**Comment by odow** [comment]
> I was going to do it like this but it seems a little impractical 

This is, in fact, exactly what @jarandh did :smile:

**Comment by odow** [comment]
It's one reason that we didn't really report computation times in the paper, because there was so much other stuff going on just so we could make this one pretty picture.

**Comment by FSchmidtDIW** [comment]
Haha :) understood! Do you think it might be worth it to create a CapExForwardPass that records iterates if the first stage is deterministic? Otherwise, I will see how the approach above works for me. Would evaluating a decision rule for the first stage be quicker than simulating a (dummy) trajectory?

**Comment by FSchmidtDIW** [comment]
Works like a charm!

I used the following to obtain a DataFrame of first-stage states by iteration:

```julia
capacities= Any[]
SDDP.train(model; forward_pass_callback = trajectory -> push!(capacities, trajectory.sampled_states[1])) # This depends on the first node being deterministic
capacity_df = reduce(vcat,[DataFrame(keys(c) .=> values(c)) for c in capacities])
```


Thanks!

**Comment by FSchmidtDIW** [comment]
Hi, sorry to reopen this. I struggle to do this in a parallel version of my code. I've tried using SharedArrays.jl but they do not admit Dict elements in the capas vector. Alternatively I could store the iterates locally on each worker and combine them later. I'm just not sure how to do that. I know, this is rather a question on distributed computing in general than one on SDDP.jl. Sorry about that :)

**Comment by odow** [comment]
What parallel scheme?

I'd advise against using the `Asynchronous` one. Use the new `Threaded` instead.

Start Julia with `julia -t N` where `N` is the number of threads, then do something like:
```julia
capacities= Any[]
my_lock = Threads.ReentrantLock();
function callback(trajectory)
    Threads.lock(my_lock) do
         push!(capacities, trajectory.sampled_states[1])
    end
    return
end
SDDP.train(model; forward_pass_callback = callback, parallel_scheme = SDDP.Threaded())
```

**Comment by FSchmidtDIW** [comment]
Great, I will try this. Indeed, I've been using the asynchronous mode and it's been working quite well but I'll make the switch to Threaded then.
Thank you very much!

**Comment by odow** [comment]
I don't have an easy way to use `forward_pass_callback` with `Distributed`. You'd probably need to use a `Channel`, but it'd get quite complicated.

**Comment by odow** [comment]
Note that threaded works best when the number of nodes is >> the number of threads.

**Comment by odow** [comment]
Yes, nodes in the graph.

The forward and backward pass are conducted asynchronously in parallel across the threads.

The differences are:

 * `SDDP.Asynchronous` has a complete copy of the graph in each process, and it periodically shares cuts between processes. This requires a lot of memory because there are multiple copies of the problem, and this has a lot of data movement between processes. But it theoretically scales to any number of processes. (Although in practice, you'll find that performance quickly tapers off with more procesess.)
 * `SDDP.Threaded` has a single copy of the model in shared memory. Each thread does forward and backward passes asynchronously and in parallel on the same graph. There is a lock at each node, so that only one thread can be solving subproblems at a node at one time. Therefore, we can have at most as many threads as there are nodes in the graph. But things work better when there are many more nodes than threads.

**Comment by FSchmidtDIW** [comment]
Very, cool! Thank you! First test run on my problem with Threaded looks very promising!

**Comment by odow** [comment]
I'll point you to the docstring: https://sddp.dev/stable/apireference/#SDDP.Threaded

It's still somewhat experimental. It should work for most standard use-cases, but if you've written any custom plugins you need to be very careful that they are themselves threadsafe.

But yeah, assuming it works and you're running on a single machine, it is much, much better than before.

**Comment by FSchmidtDIW** [comment]
Thank you! It looks like the Threaded option does not work with a RegularizedForwardPass, right? As the latter leads to significant performance gains compared to a vanilla ForwardPass in my case, it'd be interested in fixing this.
Why exactly does it fail with regularization?

**Comment by odow** [comment]
> Why exactly does it fail with regularization?

I assume we need to make it thread safe

**Comment by odow** [comment]
The issue is that we modify the first-stage for the forward pass:
https://github.com/odow/SDDP.jl/blob/aa0cf1b329f6de7fdbba23cb5dd66d7d97faeb40/src/plugins/forward_passes.jl#L356-L370

The fix might not be trivial.

**Comment by FSchmidtDIW** [comment]
I see! Well, it seems like the Threaded version without regularization is still much faster than serial with regularization, at least in my case. Thank you!
