### ISSUE TITLE
 Help with Visualizing Cuts

### ISSUE THREAD

**Issue by mcwaga** [odow/SDDP.jl#794]
Hi, I'm currently using SDDP.jl and would like to visualize the cuts generated by the value function approximation. Could you provide guidance on the best way to visualize the cuts or if there’s a built-in function I might have missed? Any example would be greatly appreciated!

**Comment by odow** [comment]
See https://sddp.dev/stable/tutorial/plotting/#Plotting-the-value-function

I probably need to improve the documentation about this.
