### ISSUE TITLE
Cut sharing with Markov policy graph

### ISSUE THREAD

**Issue by adow031** [odow/SDDP.jl#796]
I've got a SDDP model with a Markov chain used to define states and the transitions between them at each stage.

After noticing some strange behaviour in the simulated policy, the model was retrained with `refine_at_similar_nodes` set to `false`. This resolved the issue.

I've tracked the cause of the problem to there being 0 probabilities between some pairs of states at various stages. This seems to lead to SDDP not solving the model for those states, but the dual variable from the unsolved models are still being used to form cuts at other nodes in the policy graph.

I can't post a MFE here, but the above description will hopefully allow this issue to be reproduced.

**Comment by odow** [comment]
What is the issue exactly? "strange behavior" isn't very descriptive

**Comment by odow** [comment]
> This, it seems to lead to SDDP not solving the model for those states, but the dual variable from the unsolved models are still being used to form cuts at other nodes at other nodes in the policy graph.

Oooo, now I understand. The node will have a cached dual solution from a previous solve, but the incoming state variables won't line up.

**Comment by adow031** [comment]
That makes sense. I had tried to fix it myself, but decided to just post here.

**Comment by odow** [comment]
I thought I'd fixed the 0 probability arc thing. It's come up before. I can't immediately find the issue though

**Comment by odow** [comment]
Note to self: it's probably sufficient to just exclude zero-probability arcs here: 

https://github.com/odow/SDDP.jl/blob/40911556ead2a074b507d985bc0e8c65b09435d5/src/algorithm.jl#L57-L80
