### ISSUE TITLE
Restructure the examples in the documentation

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#798]
Because @bernardokp keeps banging on about it.

I don't have any immediate plans to do this because I'd prefer people focused on the tutorials which are more fleshed out.

But PRs accepted from anyone interested.

The examples are https://github.com/odow/SDDP.jl/tree/master/docs/src/examples

**Comment by odow** [comment]
As one example of a potential improvement

<img width="976" alt="image" src="https://github.com/user-attachments/assets/db9f3392-c04d-467e-a650-5c000e05ed9d">

**Comment by Thuener** [comment]
What is the goal? 
- Change the formulation? Or add this information to the page
- Show the optimal values

**Comment by bernardokp** [comment]
Hello Thuener,

in this particular case, add the information to the page and show the optimal solution and optimal values.

**Comment by Thuener** [comment]
@bernardokp please check https://github.com/odow/SDDP.jl/pull/801
