### ISSUE TITLE
Proposal: Sampling oracles

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#80]
Implement an oracle that can be used to sample the [subproblem](https://github.com/odow/SDDP.jl/blob/7f1e47140efc4fd33f0cca2be27c0331bef11203/src/SDDP.jl#L215) or [noise](https://github.com/odow/SDDP.jl/blob/7f1e47140efc4fd33f0cca2be27c0331bef11203/src/SDDP.jl#L222) in the forward pass of the algorithm. 

It probably takes the form of a new overloadable type that gets dispatched in the above functions. 

Bonus points for solving https://github.com/odow/SDDP.jl/issues/10 in addition to closing https://github.com/odow/SDDP.jl/issues/29 and #79.

Potentially looks something like

```julia
abstract type SamplingOracle end

struct Default <: SamplingOracle end
function samplenoise(::Default, m::SDDPModel, sp::JuMP.Model)
    ex = ext(sp)
    noiseidx = sample(ex.noiseprobability)
    return ex.noises[noiseidx]
end

struct Uniform <: SamplingOracle end
function samplenoise(::Uniform, m::SDDPModel, sp::JuMP.Model)
    return rand(ext(sp).noises)
end

struct Deterministic{T} <: SamplingOracle 
    data::Vector{T}
end
function samplenoise(oracle::Deterministic{T}, m::SDDPModel, sp::JuMP.Model) where T
    oracle.data[ext(sp).stage]
end

# ...

solve(m, sampling_oracle=Default())
```

**Comment by vitorlppf** [comment]
What should be the output of an oracle? Just a `Noise` object, a `Noise` object and an `Int`, or should both be possible?

In #88 I assumed the first, but consequently I'm always saving `0` in place of the index. I pondered if I should change it before committing, but decided to leave it as is.
